package com.sinoiov.vehicle.dao.beans;

import com.sinoiov.beans.BaseSerializable;
import javax.xml.bind.annotation.XmlElement;

public class Image extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ID DB Comment: ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "ID", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.OWNER_ID DB Comment: 所属对象ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "所属对象ID", required = false)
	private String ownerId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ATTACH_SOURCE_URL DB Comment: 附件原URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "附件原URL", required = false)
	private String attachSourceUrl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ATTACH_URL DB Comment: 附件URL（压缩RUL）
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "附件URL（压缩RUL）", required = false)
	private String attachUrl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ATTACH_TYPE DB Comment: 附件类型
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "附件类型", required = false)
	private String attachType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.STATUS DB Comment: 状态
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "状态", required = false)
	private String status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.OWNER_TYPE DB Comment: 所属对象类型
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "所属对象类型", required = false)
	private String ownerType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.CREATE_TIME DB Comment: 创建时间
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "创建时间", required = false)
	private Long createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.UPDATE_TIME DB Comment: 最近修改时间
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "最近修改时间", required = false)
	private Long updateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ATTACH_MINI_URL DB Comment: 附件URL（缩略URL）
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "附件URL（缩略URL）", required = false)
	private String attachMiniUrl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.IMAGES_CLEAN_STATUS DB Comment: 清洗状态（0：未清洗，1：清洗完成）
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "清洗状态（0：未清洗，1：清洗完成）", required = false)
	private String imagesCleanStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IMAGE.ATTACH_TITLE DB Comment: 附件名称
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "附件名称", required = false)
	private String attachTitle;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ID
	 * @return  the value of TB_IMAGE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ID
	 * @param id  the value for TB_IMAGE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.OWNER_ID
	 * @return  the value of TB_IMAGE.OWNER_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.OWNER_ID
	 * @param ownerId  the value for TB_IMAGE.OWNER_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldOwnerId() {
		return "OWNER_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ATTACH_SOURCE_URL
	 * @return  the value of TB_IMAGE.ATTACH_SOURCE_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getAttachSourceUrl() {
		return attachSourceUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ATTACH_SOURCE_URL
	 * @param attachSourceUrl  the value for TB_IMAGE.ATTACH_SOURCE_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAttachSourceUrl(String attachSourceUrl) {
		this.attachSourceUrl = attachSourceUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldAttachSourceUrl() {
		return "ATTACH_SOURCE_URL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ATTACH_URL
	 * @return  the value of TB_IMAGE.ATTACH_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getAttachUrl() {
		return attachUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ATTACH_URL
	 * @param attachUrl  the value for TB_IMAGE.ATTACH_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldAttachUrl() {
		return "ATTACH_URL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ATTACH_TYPE
	 * @return  the value of TB_IMAGE.ATTACH_TYPE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getAttachType() {
		return attachType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ATTACH_TYPE
	 * @param attachType  the value for TB_IMAGE.ATTACH_TYPE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldAttachType() {
		return "ATTACH_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.STATUS
	 * @return  the value of TB_IMAGE.STATUS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.STATUS
	 * @param status  the value for TB_IMAGE.STATUS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldStatus() {
		return "STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.OWNER_TYPE
	 * @return  the value of TB_IMAGE.OWNER_TYPE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getOwnerType() {
		return ownerType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.OWNER_TYPE
	 * @param ownerType  the value for TB_IMAGE.OWNER_TYPE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setOwnerType(String ownerType) {
		this.ownerType = ownerType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldOwnerType() {
		return "OWNER_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.CREATE_TIME
	 * @return  the value of TB_IMAGE.CREATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.CREATE_TIME
	 * @param createTime  the value for TB_IMAGE.CREATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldCreateTime() {
		return "CREATE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.UPDATE_TIME
	 * @return  the value of TB_IMAGE.UPDATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.UPDATE_TIME
	 * @param updateTime  the value for TB_IMAGE.UPDATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldUpdateTime() {
		return "UPDATE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ATTACH_MINI_URL
	 * @return  the value of TB_IMAGE.ATTACH_MINI_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getAttachMiniUrl() {
		return attachMiniUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ATTACH_MINI_URL
	 * @param attachMiniUrl  the value for TB_IMAGE.ATTACH_MINI_URL
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAttachMiniUrl(String attachMiniUrl) {
		this.attachMiniUrl = attachMiniUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldAttachMiniUrl() {
		return "ATTACH_MINI_URL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.IMAGES_CLEAN_STATUS
	 * @return  the value of TB_IMAGE.IMAGES_CLEAN_STATUS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getImagesCleanStatus() {
		return imagesCleanStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.IMAGES_CLEAN_STATUS
	 * @param imagesCleanStatus  the value for TB_IMAGE.IMAGES_CLEAN_STATUS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setImagesCleanStatus(String imagesCleanStatus) {
		this.imagesCleanStatus = imagesCleanStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldImagesCleanStatus() {
		return "IMAGES_CLEAN_STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IMAGE.ATTACH_TITLE
	 * @return  the value of TB_IMAGE.ATTACH_TITLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getAttachTitle() {
		return attachTitle;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IMAGE.ATTACH_TITLE
	 * @param attachTitle  the value for TB_IMAGE.ATTACH_TITLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAttachTitle(String attachTitle) {
		this.attachTitle = attachTitle;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Image() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String tableName() {
		return "TB_IMAGE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String daoInterface() {
		return "com.sinoiov.vehicle.dao.ImageDAO";
	}
}