package com.sinoiov.vehicle.dao.beans;

import com.sinoiov.beans.BaseSerializable;
import javax.xml.bind.annotation.XmlElement;

public class VehicleLine extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.ID DB Comment: ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "ID", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.V_ID DB Comment: 车辆ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "车辆ID", required = false)
	private String vId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.BASECAMP DB Comment: 大本营CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "大本营CODE", required = false)
	private String basecamp;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.BASECAMP_NAME DB Comment: 大本营NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "大本营NAME", required = false)
	private String basecampName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.LINE_CODE DB Comment: 常跑线路CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "常跑线路CODE", required = false)
	private String lineCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.LINE_NAME DB Comment: 常跑线路NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "常跑线路NAME", required = false)
	private String lineName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.START_POSITION DB Comment: 起点
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "起点", required = false)
	private String startPosition;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.END_POSTITION DB Comment: 终点
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "终点", required = false)
	private String endPostition;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.COUNT DB Comment: 次数
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "次数", required = false)
	private Long count;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.AVERAGE_DURATION DB Comment: 线路平均时长(分钟)
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "线路平均时长(分钟)", required = false)
	private Long averageDuration;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.BUSINESS_AREA DB Comment: 运营区域CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "运营区域CODE", required = false)
	private String businessArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.BUSINESS_AREA_NAME DB Comment: 运营区域NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "运营区域NAME", required = false)
	private String businessAreaName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.BUSINESS_TIME DB Comment: 运营时长
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "运营时长", required = false)
	private Long businessTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LINE.UPDATE_TIME DB Comment: 更新时间
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "更新时间", required = false)
	private Long updateTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.ID
	 * @return  the value of TB_VEHICLE_LINE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.ID
	 * @param id  the value for TB_VEHICLE_LINE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.V_ID
	 * @return  the value of TB_VEHICLE_LINE.V_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getvId() {
		return vId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.V_ID
	 * @param vId  the value for TB_VEHICLE_LINE.V_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setvId(String vId) {
		this.vId = vId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldVId() {
		return "V_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.BASECAMP
	 * @return  the value of TB_VEHICLE_LINE.BASECAMP
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getBasecamp() {
		return basecamp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.BASECAMP
	 * @param basecamp  the value for TB_VEHICLE_LINE.BASECAMP
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBasecamp(String basecamp) {
		this.basecamp = basecamp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBasecamp() {
		return "BASECAMP";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.BASECAMP_NAME
	 * @return  the value of TB_VEHICLE_LINE.BASECAMP_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getBasecampName() {
		return basecampName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.BASECAMP_NAME
	 * @param basecampName  the value for TB_VEHICLE_LINE.BASECAMP_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBasecampName(String basecampName) {
		this.basecampName = basecampName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBasecampName() {
		return "BASECAMP_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.LINE_CODE
	 * @return  the value of TB_VEHICLE_LINE.LINE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getLineCode() {
		return lineCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.LINE_CODE
	 * @param lineCode  the value for TB_VEHICLE_LINE.LINE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setLineCode(String lineCode) {
		this.lineCode = lineCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldLineCode() {
		return "LINE_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.LINE_NAME
	 * @return  the value of TB_VEHICLE_LINE.LINE_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getLineName() {
		return lineName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.LINE_NAME
	 * @param lineName  the value for TB_VEHICLE_LINE.LINE_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setLineName(String lineName) {
		this.lineName = lineName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldLineName() {
		return "LINE_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.START_POSITION
	 * @return  the value of TB_VEHICLE_LINE.START_POSITION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getStartPosition() {
		return startPosition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.START_POSITION
	 * @param startPosition  the value for TB_VEHICLE_LINE.START_POSITION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setStartPosition(String startPosition) {
		this.startPosition = startPosition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldStartPosition() {
		return "START_POSITION";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.END_POSTITION
	 * @return  the value of TB_VEHICLE_LINE.END_POSTITION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getEndPostition() {
		return endPostition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.END_POSTITION
	 * @param endPostition  the value for TB_VEHICLE_LINE.END_POSTITION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setEndPostition(String endPostition) {
		this.endPostition = endPostition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldEndPostition() {
		return "END_POSTITION";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.COUNT
	 * @return  the value of TB_VEHICLE_LINE.COUNT
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getCount() {
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.COUNT
	 * @param count  the value for TB_VEHICLE_LINE.COUNT
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setCount(Long count) {
		this.count = count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldCount() {
		return "COUNT";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.AVERAGE_DURATION
	 * @return  the value of TB_VEHICLE_LINE.AVERAGE_DURATION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getAverageDuration() {
		return averageDuration;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.AVERAGE_DURATION
	 * @param averageDuration  the value for TB_VEHICLE_LINE.AVERAGE_DURATION
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setAverageDuration(Long averageDuration) {
		this.averageDuration = averageDuration;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldAverageDuration() {
		return "AVERAGE_DURATION";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.BUSINESS_AREA
	 * @return  the value of TB_VEHICLE_LINE.BUSINESS_AREA
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getBusinessArea() {
		return businessArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.BUSINESS_AREA
	 * @param businessArea  the value for TB_VEHICLE_LINE.BUSINESS_AREA
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBusinessArea(String businessArea) {
		this.businessArea = businessArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBusinessArea() {
		return "BUSINESS_AREA";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.BUSINESS_AREA_NAME
	 * @return  the value of TB_VEHICLE_LINE.BUSINESS_AREA_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getBusinessAreaName() {
		return businessAreaName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.BUSINESS_AREA_NAME
	 * @param businessAreaName  the value for TB_VEHICLE_LINE.BUSINESS_AREA_NAME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBusinessAreaName(String businessAreaName) {
		this.businessAreaName = businessAreaName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBusinessAreaName() {
		return "BUSINESS_AREA_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.BUSINESS_TIME
	 * @return  the value of TB_VEHICLE_LINE.BUSINESS_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getBusinessTime() {
		return businessTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.BUSINESS_TIME
	 * @param businessTime  the value for TB_VEHICLE_LINE.BUSINESS_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBusinessTime(Long businessTime) {
		this.businessTime = businessTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBusinessTime() {
		return "BUSINESS_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LINE.UPDATE_TIME
	 * @return  the value of TB_VEHICLE_LINE.UPDATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LINE.UPDATE_TIME
	 * @param updateTime  the value for TB_VEHICLE_LINE.UPDATE_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldUpdateTime() {
		return "UPDATE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLine() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String tableName() {
		return "TB_VEHICLE_LINE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String daoInterface() {
		return "com.sinoiov.vehicle.dao.VehicleLineDAO";
	}
}