package com.sinoiov.vehicle.dao.beans;

import com.sinoiov.beans.BaseSerializable;
import javax.xml.bind.annotation.XmlElement;

public class VehicleLable extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.ID DB Comment: ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "ID", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.V_ID DB Comment: 车辆ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "车辆ID", required = false)
	private String vId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS DB Comment: 常跑城市
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "常跑城市", required = false)
	private String activityAreas;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS_CODE DB Comment: 常跑城市编码
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "常跑城市编码", required = false)
	private String activityAreasCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.ACTIVITY_TIME DB Comment: 在线时长（单位：分钟）
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "在线时长（单位：分钟）", required = false)
	private String activityTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_VEHICLE_LABLE.BUSINESS_TIME DB Comment: 运营时长（单位：分钟）
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	@XmlElement(name = "运营时长（单位：分钟）", required = false)
	private String businessTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.ID
	 * @return  the value of TB_VEHICLE_LABLE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.ID
	 * @param id  the value for TB_VEHICLE_LABLE.ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.V_ID
	 * @return  the value of TB_VEHICLE_LABLE.V_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getvId() {
		return vId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.V_ID
	 * @param vId  the value for TB_VEHICLE_LABLE.V_ID
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setvId(String vId) {
		this.vId = vId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldVId() {
		return "V_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS
	 * @return  the value of TB_VEHICLE_LABLE.ACTIVITY_AREAS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getActivityAreas() {
		return activityAreas;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS
	 * @param activityAreas  the value for TB_VEHICLE_LABLE.ACTIVITY_AREAS
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setActivityAreas(String activityAreas) {
		this.activityAreas = activityAreas;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldActivityAreas() {
		return "ACTIVITY_AREAS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS_CODE
	 * @return  the value of TB_VEHICLE_LABLE.ACTIVITY_AREAS_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getActivityAreasCode() {
		return activityAreasCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.ACTIVITY_AREAS_CODE
	 * @param activityAreasCode  the value for TB_VEHICLE_LABLE.ACTIVITY_AREAS_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setActivityAreasCode(String activityAreasCode) {
		this.activityAreasCode = activityAreasCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldActivityAreasCode() {
		return "ACTIVITY_AREAS_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.ACTIVITY_TIME
	 * @return  the value of TB_VEHICLE_LABLE.ACTIVITY_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getActivityTime() {
		return activityTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.ACTIVITY_TIME
	 * @param activityTime  the value for TB_VEHICLE_LABLE.ACTIVITY_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setActivityTime(String activityTime) {
		this.activityTime = activityTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldActivityTime() {
		return "ACTIVITY_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_VEHICLE_LABLE.BUSINESS_TIME
	 * @return  the value of TB_VEHICLE_LABLE.BUSINESS_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getBusinessTime() {
		return businessTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_VEHICLE_LABLE.BUSINESS_TIME
	 * @param businessTime  the value for TB_VEHICLE_LABLE.BUSINESS_TIME
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void setBusinessTime(String businessTime) {
		this.businessTime = businessTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String fieldBusinessTime() {
		return "BUSINESS_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLable() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String tableName() {
		return "TB_VEHICLE_LABLE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public static String daoInterface() {
		return "com.sinoiov.vehicle.dao.VehicleLableDAO";
	}
}