package com.ctfo.upp.gateway.fastpay.utils;

public class FastPaymentConfig {
//	private String YB_MOBILE_FAST_PAY_REQUEST_URL;
//	private String YB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL;
//	private String HTTP_TIMEOUT;
//	private String ZJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL;
//	private Integer GATEWAY_CALLBACK_RETRY_COUNT;
//	private Integer GATEWAY_CALLBACK_SLEEP_SECONDS;
//	private String YB_PC_FAST_PAY_REQUEST_URL;
//	private String YB_PC_FAST_PAY_GATEWAY_CALLBACK_URL;
//	private String YB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL;
//	private String YB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL;
//	private Integer GATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE;

//	public String getYB_MOBILE_FAST_PAY_REQUEST_URL() {
//		return YB_MOBILE_FAST_PAY_REQUEST_URL;
//	}
//
//	public void setYB_MOBILE_FAST_PAY_REQUEST_URL(String yB_MOBILE_FAST_PAY_REQUEST_URL) {
//		YB_MOBILE_FAST_PAY_REQUEST_URL = yB_MOBILE_FAST_PAY_REQUEST_URL;
//	}
//
//	public String getYB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL() {
//		return YB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL;
//	}
//
//	public void setYB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL(String yB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL) {
//		YB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL = yB_MOBILE_FAST_PAY_GATEWAY_CALLBACK_URL;
//	}


//
//	public String getHTTP_TIMEOUT() {
//		return HTTP_TIMEOUT;
//	}
//
//	public void setHTTP_TIMEOUT(String hTTP_TIMEOUT) {
//		HTTP_TIMEOUT = hTTP_TIMEOUT;
//	}
//
//	public String getZJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL() {
//		return ZJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL;
//	}
//
//	public void setZJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL(String zJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL) {
//		ZJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL = zJ_MOBILE_FAST_PAY_UPP_CALLBACL_URL;
//	}
//
//	public Integer getGATEWAY_CALLBACK_RETRY_COUNT() {
//		return GATEWAY_CALLBACK_RETRY_COUNT;
//	}
//
//	public void setGATEWAY_CALLBACK_RETRY_COUNT(Integer gATEWAY_CALLBACK_RETRY_COUNT) {
//		GATEWAY_CALLBACK_RETRY_COUNT = gATEWAY_CALLBACK_RETRY_COUNT;
//	}
//
//	public Integer getGATEWAY_CALLBACK_SLEEP_SECONDS() {
//		return GATEWAY_CALLBACK_SLEEP_SECONDS;
//	}
//
//	public void setGATEWAY_CALLBACK_SLEEP_SECONDS(Integer gATEWAY_CALLBACK_SLEEP_SECONDS) {
//		GATEWAY_CALLBACK_SLEEP_SECONDS = gATEWAY_CALLBACK_SLEEP_SECONDS;
//	}
//
//	public String getYB_PC_FAST_PAY_REQUEST_URL() {
//		return YB_PC_FAST_PAY_REQUEST_URL;
//	}
//
//	public void setYB_PC_FAST_PAY_REQUEST_URL(String yB_PC_FAST_PAY_REQUEST_URL) {
//		YB_PC_FAST_PAY_REQUEST_URL = yB_PC_FAST_PAY_REQUEST_URL;
//	}
//
//	public String getYB_PC_FAST_PAY_GATEWAY_CALLBACK_URL() {
//		return YB_PC_FAST_PAY_GATEWAY_CALLBACK_URL;
//	}
//
//	public void setYB_PC_FAST_PAY_GATEWAY_CALLBACK_URL(String yB_PC_FAST_PAY_GATEWAY_CALLBACK_URL) {
//		YB_PC_FAST_PAY_GATEWAY_CALLBACK_URL = yB_PC_FAST_PAY_GATEWAY_CALLBACK_URL;
//	}
//
//	public String getYB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL() {
//		return YB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL;
//	}
//
//	public void setYB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL(String yB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL) {
//		YB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL = yB_COMMON_FAST_PAY_TRADE_QUERY_REQUEST_URL;
//	}
//
//	public Integer getGATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE() {
//		return GATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE;
//	}
//
//	public void setGATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE(Integer gATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE) {
//		GATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE = gATEWAY_CALLBACK_HANDLE_THREAD_POOL_SIZE;
//	}
//
//	public String getYB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL() {
//		return YB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL;
//	}
//
//	public void setYB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL(String yB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL) {
//		YB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL = yB_COMMON_FAST_PAY_CLEARING_DATA_BILLS_REQUEST_URL;
//	}
}
