package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.AccountFrozenDetail;
import com.ctfo.payment.dao.beans.AccountFrozenDetailExample;
import com.ctfo.payment.dao.beans.AccountFrozenDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccountFrozenDetailDAOImpl extends SqlMapClientDaoSupport implements AccountFrozenDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public AccountFrozenDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public void insert(AccountFrozenDetail record) {
		getSqlMapClientTemplate().insert("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int updateByPrimaryKey(AccountFrozenDetail record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int updateByPrimaryKeySelective(AccountFrozenDetail record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public List selectByExample(AccountFrozenDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public AccountFrozenDetail selectByPrimaryKey(String id) {
		AccountFrozenDetail key = new AccountFrozenDetail() {
		};
		key.setId(id);
		AccountFrozenDetail record = (AccountFrozenDetail) getSqlMapClientTemplate().queryForObject("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int deleteByExample(AccountFrozenDetailExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		AccountFrozenDetail key = new AccountFrozenDetail() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int countByExample(AccountFrozenDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int updateByExampleSelective(AccountFrozenDetail record, AccountFrozenDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int updateByExample(AccountFrozenDetail record, AccountFrozenDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public List selectByExampleWithPage(AccountFrozenDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public List selectByExampleWithPage(AccountFrozenDetailExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public List getKeyBy(AccountFrozenDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_ACCOUNT_FROZEN_DETAIL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public List getKeyBy(AccountFrozenDetailExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	public int countByExample(AccountFrozenDetailExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_ACCOUNT_FROZEN_DETAIL.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	private static class UpdateByExampleParms extends AccountFrozenDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record, AccountFrozenDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}