package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.AccountFrozenDetail;
import com.ctfo.payment.dao.beans.AccountFrozenDetailExample;
import com.ctfo.payment.dao.beans.AccountFrozenDetailExampleExtended;
import java.util.List;

public interface AccountFrozenDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	void insert(AccountFrozenDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int updateByPrimaryKey(AccountFrozenDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int updateByPrimaryKeySelective(AccountFrozenDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	List selectByExample(AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	AccountFrozenDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int deleteByExample(AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int countByExample(AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int updateByExampleSelective(AccountFrozenDetail record, AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int updateByExample(AccountFrozenDetail record, AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	List selectByExampleWithPage(AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	List selectByExampleWithPage(AccountFrozenDetailExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	List getKeyBy(AccountFrozenDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	List getKeyBy(AccountFrozenDetailExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_FROZEN_DETAIL
	 * @abatorgenerated  Fri Nov 07 15:10:15 CST 2014
	 */
	int countByExample(AccountFrozenDetailExampleExtended example);
}