package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.CheckOrderDivergence;
import com.ctfo.payment.dao.beans.CheckOrderDivergenceExample;
import com.ctfo.payment.dao.beans.CheckOrderDivergenceExampleExtended;
import java.util.List;

public interface CheckOrderDivergenceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	void insert(CheckOrderDivergence record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int updateByPrimaryKey(CheckOrderDivergence record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int updateByPrimaryKeySelective(CheckOrderDivergence record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	List selectByExample(CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	CheckOrderDivergence selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int deleteByExample(CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int countByExample(CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int updateByExampleSelective(CheckOrderDivergence record,
			CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int updateByExample(CheckOrderDivergence record,
			CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	List selectByExampleWithPage(CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	List selectByExampleWithPage(
			CheckOrderDivergenceExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	List getKeyBy(CheckOrderDivergenceExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	List getKeyBy(CheckOrderDivergenceExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	int countByExample(CheckOrderDivergenceExampleExtended example);
}