package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.CheckOrderDivergence;
import com.ctfo.payment.dao.beans.CheckOrderDivergenceExample;
import com.ctfo.payment.dao.beans.CheckOrderDivergenceExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CheckOrderDivergenceDAOImpl extends SqlMapClientDaoSupport implements CheckOrderDivergenceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public CheckOrderDivergenceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public void insert(CheckOrderDivergence record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int updateByPrimaryKey(CheckOrderDivergence record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int updateByPrimaryKeySelective(CheckOrderDivergence record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public List selectByExample(CheckOrderDivergenceExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public CheckOrderDivergence selectByPrimaryKey(String id) {
		CheckOrderDivergence key = new CheckOrderDivergence() {
		};
		key.setId(id);
		CheckOrderDivergence record = (CheckOrderDivergence) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int deleteByExample(CheckOrderDivergenceExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		CheckOrderDivergence key = new CheckOrderDivergence() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int countByExample(CheckOrderDivergenceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int updateByExampleSelective(CheckOrderDivergence record,
			CheckOrderDivergenceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int updateByExample(CheckOrderDivergence record,
			CheckOrderDivergenceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public List selectByExampleWithPage(CheckOrderDivergenceExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public List selectByExampleWithPage(
			CheckOrderDivergenceExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public List getKeyBy(CheckOrderDivergenceExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_CHECK_ORDER_DIVERGENCE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public List getKeyBy(CheckOrderDivergenceExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	public int countByExample(CheckOrderDivergenceExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_CHECK_ORDER_DIVERGENCE.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_CHECK_ORDER_DIVERGENCE
	 * @abatorgenerated  Mon Feb 02 20:41:09 CST 2015
	 */
	private static class UpdateByExampleParms extends
			CheckOrderDivergenceExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				CheckOrderDivergenceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}