package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.HOrderInfo;
import com.ctfo.payment.dao.beans.HOrderInfoExample;
import com.ctfo.payment.dao.beans.HOrderInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HOrderInfoDAOImpl extends SqlMapClientDaoSupport implements HOrderInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public HOrderInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public void insert(HOrderInfo record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int updateByPrimaryKey(HOrderInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int updateByPrimaryKeySelective(HOrderInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public List selectByExample(HOrderInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public HOrderInfo selectByPrimaryKey(String id) {
		HOrderInfo key = new HOrderInfo() {
		};
		key.setId(id);
		HOrderInfo record = (HOrderInfo) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int deleteByExample(HOrderInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		HOrderInfo key = new HOrderInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int countByExample(HOrderInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int updateByExampleSelective(HOrderInfo record,
			HOrderInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int updateByExample(HOrderInfo record, HOrderInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public List selectByExampleWithPage(HOrderInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public List selectByExampleWithPage(
			HOrderInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public List getKeyBy(HOrderInfoExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectKeyBy",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_PAY_ORDER_HISTORY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public List getKeyBy(HOrderInfoExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	public int countByExample(HOrderInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_PAY_ORDER_HISTORY.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_PAY_ORDER_HISTORY
	 * @abatorgenerated  Tue Jul 21 14:56:04 CST 2015
	 */
	private static class UpdateByExampleParms extends HOrderInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, HOrderInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}