package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.HPaymentTrade;
import com.ctfo.payment.dao.beans.HPaymentTradeExample;
import com.ctfo.payment.dao.beans.HPaymentTradeExampleExtended;
import java.util.List;

public interface HPaymentTradeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	void insert(HPaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int updateByPrimaryKey(HPaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int updateByPrimaryKeySelective(HPaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	List selectByExample(HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	HPaymentTrade selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int deleteByExample(HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int countByExample(HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int updateByExampleSelective(HPaymentTrade record,
			HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int updateByExample(HPaymentTrade record, HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	List selectByExampleWithPage(HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	List selectByExampleWithPage(HPaymentTradeExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	List getKeyBy(HPaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	List getKeyBy(HPaymentTradeExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE_HISTORY
	 * @abatorgenerated  Thu May 21 15:53:47 CST 2015
	 */
	int countByExample(HPaymentTradeExampleExtended example);
}