package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.MainWithThirdPartyAccount;
import com.ctfo.payment.dao.beans.MainWithThirdPartyAccountExample;
import com.ctfo.payment.dao.beans.MainWithThirdPartyAccountExampleExtended;
import java.util.List;

public interface MainWithThirdPartyAccountDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	void insert(MainWithThirdPartyAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int updateByPrimaryKey(MainWithThirdPartyAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int updateByPrimaryKeySelective(MainWithThirdPartyAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	List selectByExample(MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	MainWithThirdPartyAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int deleteByExample(MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int countByExample(MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int updateByExampleSelective(MainWithThirdPartyAccount record,
			MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int updateByExample(MainWithThirdPartyAccount record,
			MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	List selectByExampleWithPage(MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	List selectByExampleWithPage(
			MainWithThirdPartyAccountExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	List getKeyBy(MainWithThirdPartyAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	List getKeyBy(MainWithThirdPartyAccountExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CKECK_ACCOUNT_MESS
	 * @abatorgenerated  Thu Jan 22 14:02:16 CST 2015
	 */
	int countByExample(MainWithThirdPartyAccountExampleExtended example);
}