package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.OfflineRechargeApplyApproval;
import com.ctfo.payment.dao.beans.OfflineRechargeApplyApprovalExample;
import com.ctfo.payment.dao.beans.OfflineRechargeApplyApprovalExampleExtended;
import java.util.List;

public interface OfflineRechargeApplyApprovalDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    void insert(OfflineRechargeApplyApproval record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int updateByPrimaryKey(OfflineRechargeApplyApproval record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int updateByPrimaryKeySelective(OfflineRechargeApplyApproval record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    List selectByExample(OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    OfflineRechargeApplyApproval selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int deleteByExample(OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int countByExample(OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int updateByExampleSelective(OfflineRechargeApplyApproval record, OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int updateByExample(OfflineRechargeApplyApproval record, OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    List selectByExampleWithPage(OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    List selectByExampleWithPage(OfflineRechargeApplyApprovalExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    List getKeyBy(OfflineRechargeApplyApprovalExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    List getKeyBy(OfflineRechargeApplyApprovalExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_INFO
     *
     * @abatorgenerated Mon Nov 03 11:52:23 CST 2014
     */
    int countByExample(OfflineRechargeApplyApprovalExampleExtended example);
}