package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.OfflineRechargeApply;
import com.ctfo.payment.dao.beans.OfflineRechargeApplyExample;
import com.ctfo.payment.dao.beans.OfflineRechargeApplyExampleExtended;
import java.util.List;

public interface OfflineRechargeApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	void insert(OfflineRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int updateByPrimaryKey(OfflineRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int updateByPrimaryKeySelective(OfflineRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	List selectByExample(OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	OfflineRechargeApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int deleteByExample(OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int countByExample(OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int updateByExampleSelective(OfflineRechargeApply record,
			OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int updateByExample(OfflineRechargeApply record,
			OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	List selectByExampleWithPage(OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	List selectByExampleWithPage(
			OfflineRechargeApplyExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	List getKeyBy(OfflineRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	List getKeyBy(OfflineRechargeApplyExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_OFFLINE_TRADE_APPLY
	 * @abatorgenerated  Wed Jul 29 11:07:39 CST 2015
	 */
	int countByExample(OfflineRechargeApplyExampleExtended example);
}