package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.OrderInfo;
import com.ctfo.payment.dao.beans.OrderInfoExample;
import com.ctfo.payment.dao.beans.OrderInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderInfoDAOImpl extends SqlMapClientDaoSupport implements OrderInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public OrderInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public void insert(OrderInfo record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_PAY_ORDER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int updateByPrimaryKey(OrderInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int updateByPrimaryKeySelective(OrderInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public List selectByExample(OrderInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public OrderInfo selectByPrimaryKey(String id) {
		OrderInfo key = new OrderInfo() {
		};
		key.setId(id);
		OrderInfo record = (OrderInfo) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_PAY_ORDER.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int deleteByExample(OrderInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_ORDER.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		OrderInfo key = new OrderInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_ORDER.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int countByExample(OrderInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PAY_ORDER.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int updateByExampleSelective(OrderInfo record,
			OrderInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int updateByExample(OrderInfo record, OrderInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_ORDER.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public List selectByExampleWithPage(OrderInfoExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_ORDER.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public List selectByExampleWithPage(OrderInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public List getKeyBy(OrderInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_ORDER.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_PAY_ORDER";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public List getKeyBy(OrderInfoExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_ORDER.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	public int countByExample(OrderInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PAY_ORDER.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_PAY_ORDER
	 * @abatorgenerated  Tue Jul 21 14:56:05 CST 2015
	 */
	private static class UpdateByExampleParms extends OrderInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, OrderInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}