package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.PaymentTrade;
import com.ctfo.payment.dao.beans.PaymentTradeExample;
import com.ctfo.payment.dao.beans.PaymentTradeExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PaymentTradeDAOImpl extends SqlMapClientDaoSupport implements PaymentTradeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public PaymentTradeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public void insert(PaymentTrade record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_PAY_TRADE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int updateByPrimaryKey(PaymentTrade record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_TRADE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int updateByPrimaryKeySelective(PaymentTrade record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_TRADE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public List selectByExample(PaymentTradeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_TRADE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public PaymentTrade selectByPrimaryKey(String id) {
		PaymentTrade key = new PaymentTrade() {
		};
		key.setId(id);
		PaymentTrade record = (PaymentTrade) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_PAY_TRADE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int deleteByExample(PaymentTradeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_TRADE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		PaymentTrade key = new PaymentTrade() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_PAY_TRADE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int countByExample(PaymentTradeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PAY_TRADE.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int updateByExampleSelective(PaymentTrade record,
			PaymentTradeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_TRADE.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int updateByExample(PaymentTrade record, PaymentTradeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_PAY_TRADE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public List selectByExampleWithPage(PaymentTradeExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_TRADE.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public List selectByExampleWithPage(
			PaymentTradeExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_TRADE.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public List getKeyBy(PaymentTradeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_PAY_TRADE.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_PAY_TRADE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public List getKeyBy(PaymentTradeExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_PAY_TRADE.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	public int countByExample(PaymentTradeExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_PAY_TRADE.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	private static class UpdateByExampleParms extends PaymentTradeExample {
		private Object record;

		public UpdateByExampleParms(Object record, PaymentTradeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}