package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.PaymentTrade;
import com.ctfo.payment.dao.beans.PaymentTradeExample;
import com.ctfo.payment.dao.beans.PaymentTradeExampleExtended;
import java.util.List;

public interface PaymentTradeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	void insert(PaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int updateByPrimaryKey(PaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int updateByPrimaryKeySelective(PaymentTrade record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	List selectByExample(PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	PaymentTrade selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int deleteByExample(PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int countByExample(PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int updateByExampleSelective(PaymentTrade record,
			PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int updateByExample(PaymentTrade record, PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	List selectByExampleWithPage(PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	List selectByExampleWithPage(PaymentTradeExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	List getKeyBy(PaymentTradeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	List getKeyBy(PaymentTradeExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_PAY_TRADE
	 * @abatorgenerated  Thu May 21 15:53:46 CST 2015
	 */
	int countByExample(PaymentTradeExampleExtended example);
}