package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.UnbalanceDetailWithBusPlatform;
import com.ctfo.payment.dao.beans.UnbalanceDetailWithBusPlatformExample;
import com.ctfo.payment.dao.beans.UnbalanceDetailWithBusPlatformExampleExtended;
import java.util.List;

public interface UnbalanceDetailWithBusPlatformDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	void insert(UnbalanceDetailWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int updateByPrimaryKey(UnbalanceDetailWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int updateByPrimaryKeySelective(UnbalanceDetailWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	List selectByExample(UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	UnbalanceDetailWithBusPlatform selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int deleteByExample(UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int countByExample(UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int updateByExampleSelective(UnbalanceDetailWithBusPlatform record,
			UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int updateByExample(UnbalanceDetailWithBusPlatform record,
			UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	List selectByExampleWithPage(UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	List selectByExampleWithPage(
			UnbalanceDetailWithBusPlatformExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	List getKeyBy(UnbalanceDetailWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	List getKeyBy(UnbalanceDetailWithBusPlatformExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
	 * @abatorgenerated  Thu Jan 22 14:02:15 CST 2015
	 */
	int countByExample(UnbalanceDetailWithBusPlatformExampleExtended example);
}