package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.UnbalanceHandlerWithBusPlatform;
import com.ctfo.payment.dao.beans.UnbalanceHandlerWithBusPlatformExample;
import com.ctfo.payment.dao.beans.UnbalanceHandlerWithBusPlatformExampleExtended;
import java.util.List;

public interface UnbalanceHandlerWithBusPlatformDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	void insert(UnbalanceHandlerWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int updateByPrimaryKey(UnbalanceHandlerWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int updateByPrimaryKeySelective(UnbalanceHandlerWithBusPlatform record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	List selectByExample(UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	UnbalanceHandlerWithBusPlatform selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int deleteByExample(UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int countByExample(UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int updateByExampleSelective(UnbalanceHandlerWithBusPlatform record,
			UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int updateByExample(UnbalanceHandlerWithBusPlatform record,
			UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	List selectByExampleWithPage(UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	List selectByExampleWithPage(
			UnbalanceHandlerWithBusPlatformExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	List getKeyBy(UnbalanceHandlerWithBusPlatformExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	List getKeyBy(UnbalanceHandlerWithBusPlatformExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CHECKORDER_HANDLE
	 * @abatorgenerated  Thu Jan 22 14:02:13 CST 2015
	 */
	int countByExample(UnbalanceHandlerWithBusPlatformExampleExtended example);
}