package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.UPPStoreCheckBatch;
import com.ctfo.payment.dao.beans.UPPStoreCheckBatchExample;
import com.ctfo.payment.dao.beans.UPPStoreCheckBatchExampleExtended;
import java.util.List;

public interface UPPStoreCheckBatchDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    void insert(UPPStoreCheckBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int updateByPrimaryKey(UPPStoreCheckBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int updateByPrimaryKeySelective(UPPStoreCheckBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    List selectByExample(UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    UPPStoreCheckBatch selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int deleteByExample(UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int countByExample(UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int updateByExampleSelective(UPPStoreCheckBatch record, UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int updateByExample(UPPStoreCheckBatch record, UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    List selectByExampleWithPage(UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    List selectByExampleWithPage(UPPStoreCheckBatchExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    List getKeyBy(UPPStoreCheckBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    List getKeyBy(UPPStoreCheckBatchExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_STORE_CHECK_BATCH
     *
     * @abatorgenerated Sat Jan 31 10:59:05 CST 2015
     */
    int countByExample(UPPStoreCheckBatchExampleExtended example);
}