package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.WithdrawCashApply;
import com.ctfo.payment.dao.beans.WithdrawCashApplyExample;
import com.ctfo.payment.dao.beans.WithdrawCashApplyExampleExtended;
import java.util.List;

public interface WithdrawCashApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	void insert(WithdrawCashApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int updateByPrimaryKey(WithdrawCashApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int updateByPrimaryKeySelective(WithdrawCashApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	List selectByExample(WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	WithdrawCashApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int deleteByExample(WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int countByExample(WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int updateByExampleSelective(WithdrawCashApply record, WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int updateByExample(WithdrawCashApply record, WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	List selectByExampleWithPage(WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	List selectByExampleWithPage(WithdrawCashApplyExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	List getKeyBy(WithdrawCashApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	List getKeyBy(WithdrawCashApplyExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	int countByExample(WithdrawCashApplyExampleExtended example);
}