package com.ctfo.upp.accountservice.payment.dao;

import com.ctfo.payment.dao.beans.WithdrawCashApply;
import com.ctfo.payment.dao.beans.WithdrawCashApplyExample;
import com.ctfo.payment.dao.beans.WithdrawCashApplyExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WithdrawCashApplyDAOImpl extends SqlMapClientDaoSupport implements WithdrawCashApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public WithdrawCashApplyDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public void insert(WithdrawCashApply record) {
		getSqlMapClientTemplate().insert("TB_TAKECASH_APPLY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int updateByPrimaryKey(WithdrawCashApply record) {
		int rows = getSqlMapClientTemplate().update("TB_TAKECASH_APPLY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int updateByPrimaryKeySelective(WithdrawCashApply record) {
		int rows = getSqlMapClientTemplate().update("TB_TAKECASH_APPLY.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public List selectByExample(WithdrawCashApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_TAKECASH_APPLY.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public WithdrawCashApply selectByPrimaryKey(String id) {
		WithdrawCashApply key = new WithdrawCashApply() {
		};
		key.setId(id);
		WithdrawCashApply record = (WithdrawCashApply) getSqlMapClientTemplate().queryForObject("TB_TAKECASH_APPLY.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int deleteByExample(WithdrawCashApplyExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_TAKECASH_APPLY.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		WithdrawCashApply key = new WithdrawCashApply() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("TB_TAKECASH_APPLY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int countByExample(WithdrawCashApplyExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_TAKECASH_APPLY.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int updateByExampleSelective(WithdrawCashApply record, WithdrawCashApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_TAKECASH_APPLY.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int updateByExample(WithdrawCashApply record, WithdrawCashApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_TAKECASH_APPLY.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public List selectByExampleWithPage(WithdrawCashApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_TAKECASH_APPLY.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public List selectByExampleWithPage(WithdrawCashApplyExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList("TB_TAKECASH_APPLY.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public List getKeyBy(WithdrawCashApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_TAKECASH_APPLY.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public String getNameSpace() {
		return "TB_TAKECASH_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public List getKeyBy(WithdrawCashApplyExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList("TB_TAKECASH_APPLY.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	public int countByExample(WithdrawCashApplyExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_TAKECASH_APPLY.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_TAKECASH_APPLY
	 * @abatorgenerated  Mon Nov 03 11:52:21 CST 2014
	 */
	private static class UpdateByExampleParms extends WithdrawCashApplyExample {
		private Object record;

		public UpdateByExampleParms(Object record, WithdrawCashApplyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}