package com.ctfo.account.dao.beans;

import com.ctfo.upp.models.BaseSerializable;
import javax.xml.bind.annotation.XmlElement;

public class AuthenApplyInfo extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.ID DB Comment: 
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.INSIDE_ACCOUNT_NO DB Comment: 内部账号
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "内部账号", required = false)
	private String insideAccountNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCONT_ID DB Comment: 对应账户的ID
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "对应账户的ID", required = false)
	private String accontId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TYPE DB Comment: 申请类型：1.开户申请，2.实名认证申请
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "申请类型：1.开户申请，2.实名认证申请", required = false)
	private String applyType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_STATUS DB Comment: 该申请的状态
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "该申请的状态", required = false)
	private String applyStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.USER_NAME DB Comment: 实名认证请求时必填
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "实名认证请求时必填", required = false)
	private String userName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.MOBILE_NO DB Comment: 绑定手机号
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "绑定手机号", required = false)
	private String mobileNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_TYPE DB Comment: 用户身份证件类型
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "用户身份证件类型", required = false)
	private String idcardType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_NO DB Comment: 实名认证时必填
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "实名认证时必填", required = false)
	private String idcardNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_PASSWORD DB Comment: 加密后的用户交易密码
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "加密后的用户交易密码", required = false)
	private String payPassword;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANKCARD_NO DB Comment: 银行卡号，实名认证请求时必填，用户作为提现卡号
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "银行卡号，实名认证请求时必填，用户作为提现卡号", required = false)
	private String bankcardNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANK_CODE DB Comment: 
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "", required = false)
	private String bankCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_NAME DB Comment: 开户行名称
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "开户行名称", required = false)
	private String branchBankName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_PROVINCE DB Comment: 开户行省份编码
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "开户行省份编码", required = false)
	private String branchBankProvince;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_CITY DB Comment: 开户行城市编码
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "开户行城市编码", required = false)
	private String branchBankCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_ENDDATE DB Comment: 身份证有效期，非必填
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "身份证有效期，非必填", required = false)
	private String idcardEnddate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TIME DB Comment: 请求时间，必填
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "请求时间，必填", required = false)
	private Long applyTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_CONFIRM_DATE DB Comment: 调用支付平台后，支付平台回传确认的时间
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "调用支付平台后，支付平台回传确认的时间", required = false)
	private Long payConfirmDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.PROVIDER_TYPE DB Comment: 标识第三方支付平台，如：易宝、支付宝或中交支付
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "标识第三方支付平台，如：易宝、支付宝或中交支付", required = false)
	private String providerType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.EXTERNAL_NO DB Comment: 第三方支付给定的交易流水号
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "第三方支付给定的交易流水号", required = false)
	private String externalNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_STATUS DB Comment: 存放支付机构返回的响应状态
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "存放支付机构返回的响应状态", required = false)
	private String payStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.REMARK DB Comment: 
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "", required = false)
	private String remark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCOUNT_NO_TYPE DB Comment: 0普通账号，1对公账号
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "0普通账号，1对公账号", required = false)
	private String accountNoType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column UPP.TB_UPP_AUTHENTICA_APPLY.IS_MAIN_CARD DB Comment: 0不是主卡，1是主卡
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	@XmlElement(name = "0不是主卡，1是主卡", required = false)
	private String isMainCard;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ID
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.ID
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ID
	 * @param id  the value for UPP.TB_UPP_AUTHENTICA_APPLY.ID
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.INSIDE_ACCOUNT_NO
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.INSIDE_ACCOUNT_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getInsideAccountNo() {
		return insideAccountNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.INSIDE_ACCOUNT_NO
	 * @param insideAccountNo  the value for UPP.TB_UPP_AUTHENTICA_APPLY.INSIDE_ACCOUNT_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setInsideAccountNo(String insideAccountNo) {
		this.insideAccountNo = insideAccountNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldInsideAccountNo() {
		return "INSIDE_ACCOUNT_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCONT_ID
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.ACCONT_ID
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getAccontId() {
		return accontId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCONT_ID
	 * @param accontId  the value for UPP.TB_UPP_AUTHENTICA_APPLY.ACCONT_ID
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setAccontId(String accontId) {
		this.accontId = accontId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldAccontId() {
		return "ACCONT_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TYPE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getApplyType() {
		return applyType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TYPE
	 * @param applyType  the value for UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldApplyType() {
		return "APPLY_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_STATUS
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_STATUS
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getApplyStatus() {
		return applyStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_STATUS
	 * @param applyStatus  the value for UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_STATUS
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldApplyStatus() {
		return "APPLY_STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.USER_NAME
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.USER_NAME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.USER_NAME
	 * @param userName  the value for UPP.TB_UPP_AUTHENTICA_APPLY.USER_NAME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldUserName() {
		return "USER_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.MOBILE_NO
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.MOBILE_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.MOBILE_NO
	 * @param mobileNo  the value for UPP.TB_UPP_AUTHENTICA_APPLY.MOBILE_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldMobileNo() {
		return "MOBILE_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_TYPE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getIdcardType() {
		return idcardType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_TYPE
	 * @param idcardType  the value for UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setIdcardType(String idcardType) {
		this.idcardType = idcardType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldIdcardType() {
		return "IDCARD_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_NO
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getIdcardNo() {
		return idcardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_NO
	 * @param idcardNo  the value for UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setIdcardNo(String idcardNo) {
		this.idcardNo = idcardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldIdcardNo() {
		return "IDCARD_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_PASSWORD
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.PAY_PASSWORD
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getPayPassword() {
		return payPassword;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_PASSWORD
	 * @param payPassword  the value for UPP.TB_UPP_AUTHENTICA_APPLY.PAY_PASSWORD
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setPayPassword(String payPassword) {
		this.payPassword = payPassword;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldPayPassword() {
		return "PAY_PASSWORD";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANKCARD_NO
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.BANKCARD_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getBankcardNo() {
		return bankcardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANKCARD_NO
	 * @param bankcardNo  the value for UPP.TB_UPP_AUTHENTICA_APPLY.BANKCARD_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setBankcardNo(String bankcardNo) {
		this.bankcardNo = bankcardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldBankcardNo() {
		return "BANKCARD_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANK_CODE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.BANK_CODE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BANK_CODE
	 * @param bankCode  the value for UPP.TB_UPP_AUTHENTICA_APPLY.BANK_CODE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldBankCode() {
		return "BANK_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_NAME
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_NAME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getBranchBankName() {
		return branchBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_NAME
	 * @param branchBankName  the value for UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_NAME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setBranchBankName(String branchBankName) {
		this.branchBankName = branchBankName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldBranchBankName() {
		return "BRANCH_BANK_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_PROVINCE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_PROVINCE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getBranchBankProvince() {
		return branchBankProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_PROVINCE
	 * @param branchBankProvince  the value for UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_PROVINCE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setBranchBankProvince(String branchBankProvince) {
		this.branchBankProvince = branchBankProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldBranchBankProvince() {
		return "BRANCH_BANK_PROVINCE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_CITY
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_CITY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getBranchBankCity() {
		return branchBankCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_CITY
	 * @param branchBankCity  the value for UPP.TB_UPP_AUTHENTICA_APPLY.BRANCH_BANK_CITY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setBranchBankCity(String branchBankCity) {
		this.branchBankCity = branchBankCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldBranchBankCity() {
		return "BRANCH_BANK_CITY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_ENDDATE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_ENDDATE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getIdcardEnddate() {
		return idcardEnddate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_ENDDATE
	 * @param idcardEnddate  the value for UPP.TB_UPP_AUTHENTICA_APPLY.IDCARD_ENDDATE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setIdcardEnddate(String idcardEnddate) {
		this.idcardEnddate = idcardEnddate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldIdcardEnddate() {
		return "IDCARD_ENDDATE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TIME
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TIME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public Long getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TIME
	 * @param applyTime  the value for UPP.TB_UPP_AUTHENTICA_APPLY.APPLY_TIME
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setApplyTime(Long applyTime) {
		this.applyTime = applyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldApplyTime() {
		return "APPLY_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_CONFIRM_DATE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.PAY_CONFIRM_DATE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public Long getPayConfirmDate() {
		return payConfirmDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_CONFIRM_DATE
	 * @param payConfirmDate  the value for UPP.TB_UPP_AUTHENTICA_APPLY.PAY_CONFIRM_DATE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setPayConfirmDate(Long payConfirmDate) {
		this.payConfirmDate = payConfirmDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldPayConfirmDate() {
		return "PAY_CONFIRM_DATE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PROVIDER_TYPE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.PROVIDER_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getProviderType() {
		return providerType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PROVIDER_TYPE
	 * @param providerType  the value for UPP.TB_UPP_AUTHENTICA_APPLY.PROVIDER_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setProviderType(String providerType) {
		this.providerType = providerType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldProviderType() {
		return "PROVIDER_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.EXTERNAL_NO
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.EXTERNAL_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getExternalNo() {
		return externalNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.EXTERNAL_NO
	 * @param externalNo  the value for UPP.TB_UPP_AUTHENTICA_APPLY.EXTERNAL_NO
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setExternalNo(String externalNo) {
		this.externalNo = externalNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldExternalNo() {
		return "EXTERNAL_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_STATUS
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.PAY_STATUS
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.PAY_STATUS
	 * @param payStatus  the value for UPP.TB_UPP_AUTHENTICA_APPLY.PAY_STATUS
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldPayStatus() {
		return "PAY_STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.REMARK
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.REMARK
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.REMARK
	 * @param remark  the value for UPP.TB_UPP_AUTHENTICA_APPLY.REMARK
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldRemark() {
		return "REMARK";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCOUNT_NO_TYPE
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.ACCOUNT_NO_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getAccountNoType() {
		return accountNoType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.ACCOUNT_NO_TYPE
	 * @param accountNoType  the value for UPP.TB_UPP_AUTHENTICA_APPLY.ACCOUNT_NO_TYPE
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setAccountNoType(String accountNoType) {
		this.accountNoType = accountNoType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldAccountNoType() {
		return "ACCOUNT_NO_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IS_MAIN_CARD
	 * @return  the value of UPP.TB_UPP_AUTHENTICA_APPLY.IS_MAIN_CARD
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getIsMainCard() {
		return isMainCard;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column UPP.TB_UPP_AUTHENTICA_APPLY.IS_MAIN_CARD
	 * @param isMainCard  the value for UPP.TB_UPP_AUTHENTICA_APPLY.IS_MAIN_CARD
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void setIsMainCard(String isMainCard) {
		this.isMainCard = isMainCard;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String fieldIsMainCard() {
		return "IS_MAIN_CARD";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public AuthenApplyInfo() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String tableName() {
		return "TB_UPP_AUTHENTICA_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public static String daoInterface() {
		return "com.ctfo.upp.accountservice.account.dao.AuthenApplyInfoDAO";
	}
}