package com.ctfo.account.dao.beans;

import com.ctfo.upp.models.BaseSerializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlElement;

public class DetailWithThirdPartyAccount extends BaseSerializable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ID
     * DB Comment: 
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="", required=false )
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.TB__ID
     * DB Comment: 主键，对账ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="主键，对账ID", required=false )
    private String tbId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TRADE_ID
     * DB Comment: 该交易在支付平台的唯一标识
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="该交易在支付平台的唯一标识", required=false )
    private String payTradeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.EXTERNAL_NO
     * DB Comment: 
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="", required=false )
    private String externalNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_AMOUNT
     * DB Comment: 支付金额
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="支付金额", required=false )
    private BigDecimal payAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_POUND_SCALE
     * DB Comment: 支付手续费
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="支付手续费", required=false )
    private BigDecimal payPoundScale;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TIME
     * DB Comment: 支付时间
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="支付时间", required=false )
    private Long payTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PROVIDER_TYPE
     * DB Comment: 标识第三方支付平台
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="标识第三方支付平台", required=false )
    private String providerType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_CHANNEL
     * DB Comment: wap或页面支付
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="wap或页面支付", required=false )
    private String payChannel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_STATUS
     * DB Comment: 
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="", required=false )
    private String payStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ACCOUNT_DATE
     * DB Comment: 
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="", required=false )
    private String accountDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TIME
     * DB Comment: 
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="", required=false )
    private Long checkTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_STATUS
     * DB Comment: 成功或失败
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="成功或失败", required=false )
    private String checkStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BATCH_NO
     * DB Comment: 对账批次号
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="对账批次号", required=false )
    private String batchNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.INSIDE_EXTERNAL_NO
     * DB Comment: 内部交易流水，唯一标识
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="内部交易流水，唯一标识", required=false )
    private String insideExternalNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BANK_CODE
     * DB Comment: 直连网银的支付方式改字段不为空，标识使用哪个银行的网银支付
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="直连网银的支付方式改字段不为空，标识使用哪个银行的网银支付", required=false )
    private String bankCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.REMARKS
     * DB Comment: 备注
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="备注", required=false )
    private String remarks;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TYPE
     * DB Comment: 对账方式,自动对账或手工
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    @XmlElement(name="对账方式,自动对账或手工", required=false )
    private String checkType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ID
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ID
     *
     * @param id the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldId() {
        return "ID";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.TB__ID
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.TB__ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getTbId() {
        return tbId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.TB__ID
     *
     * @param tbId the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.TB__ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setTbId(String tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldTbId() {
        return "TB__ID";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TRADE_ID
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TRADE_ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getPayTradeId() {
        return payTradeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TRADE_ID
     *
     * @param payTradeId the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TRADE_ID
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayTradeId(String payTradeId) {
        this.payTradeId = payTradeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayTradeId() {
        return "PAY_TRADE_ID";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.EXTERNAL_NO
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.EXTERNAL_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getExternalNo() {
        return externalNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.EXTERNAL_NO
     *
     * @param externalNo the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.EXTERNAL_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldExternalNo() {
        return "EXTERNAL_NO";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_AMOUNT
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_AMOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_AMOUNT
     *
     * @param payAmount the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_AMOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayAmount() {
        return "PAY_AMOUNT";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_POUND_SCALE
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_POUND_SCALE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public BigDecimal getPayPoundScale() {
        return payPoundScale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_POUND_SCALE
     *
     * @param payPoundScale the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_POUND_SCALE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayPoundScale(BigDecimal payPoundScale) {
        this.payPoundScale = payPoundScale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayPoundScale() {
        return "PAY_POUND_SCALE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TIME
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TIME
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TIME
     *
     * @param payTime the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_TIME
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayTime() {
        return "PAY_TIME";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PROVIDER_TYPE
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PROVIDER_TYPE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getProviderType() {
        return providerType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PROVIDER_TYPE
     *
     * @param providerType the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PROVIDER_TYPE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setProviderType(String providerType) {
        this.providerType = providerType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldProviderType() {
        return "PROVIDER_TYPE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_CHANNEL
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_CHANNEL
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_CHANNEL
     *
     * @param payChannel the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_CHANNEL
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayChannel() {
        return "PAY_CHANNEL";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_STATUS
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_STATUS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_STATUS
     *
     * @param payStatus the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.PAY_STATUS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldPayStatus() {
        return "PAY_STATUS";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ACCOUNT_DATE
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.ACCOUNT_DATE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.ACCOUNT_DATE
     *
     * @param accountDate the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.ACCOUNT_DATE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setAccountDate(String accountDate) {
        this.accountDate = accountDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldAccountDate() {
        return "ACCOUNT_DATE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TIME
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TIME
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public Long getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TIME
     *
     * @param checkTime the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TIME
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setCheckTime(Long checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldCheckTime() {
        return "CHECK_TIME";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_STATUS
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_STATUS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_STATUS
     *
     * @param checkStatus the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_STATUS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldCheckStatus() {
        return "CHECK_STATUS";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BATCH_NO
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.BATCH_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BATCH_NO
     *
     * @param batchNo the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.BATCH_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldBatchNo() {
        return "BATCH_NO";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.INSIDE_EXTERNAL_NO
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.INSIDE_EXTERNAL_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getInsideExternalNo() {
        return insideExternalNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.INSIDE_EXTERNAL_NO
     *
     * @param insideExternalNo the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.INSIDE_EXTERNAL_NO
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setInsideExternalNo(String insideExternalNo) {
        this.insideExternalNo = insideExternalNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldInsideExternalNo() {
        return "INSIDE_EXTERNAL_NO";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BANK_CODE
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.BANK_CODE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.BANK_CODE
     *
     * @param bankCode the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.BANK_CODE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldBankCode() {
        return "BANK_CODE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.REMARKS
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.REMARKS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.REMARKS
     *
     * @param remarks the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.REMARKS
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldRemarks() {
        return "REMARKS";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TYPE
     *
     * @return the value of UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TYPE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TYPE
     *
     * @param checkType the value for UPP.TB_UPP_CHECK_PAY_ACCOUNT.CHECK_TYPE
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void setCheckType(String checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String fieldCheckType() {
        return "CHECK_TYPE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public DetailWithThirdPartyAccount() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String tableName() {
        return "TB_UPP_CHECK_PAY_ACCOUNT";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public static String daoInterface() {
        return "com.ctfo.upp.accountservice.account.dao.DetailWithThirdPartyAccountDAO";
    }
}