package com.ctfo.account.dao.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SpecialAccountDetailExample implements Serializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected List oredCriteria;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected int skipNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected int endNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected int limitNum;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public SpecialAccountDetailExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected SpecialAccountDetailExample(SpecialAccountDetailExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public static String tableName() {
		return "TB_UPP_SUB_BOOK_ACCOUNT_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.upp.accountservice.account.dao.SpecialAccountDetailDAO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void setSkipNum(int skipNum) {
		this.skipNum = skipNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int getSkipNum() {
		return this.skipNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void setEndNum(int endNum) {
		this.endNum = endNum;
		this.limitNum = this.endNum - this.skipNum - 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int getEndNum() {
		return this.endNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void setLimitNum(int limitNum) {
		this.limitNum = limitNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int getLimitNum() {
		return this.limitNum;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public static class Criteria implements Serializable {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andInsideExternalNoIsNull() {
			addCriterion("INSIDE_EXTERNAL_NO is null");
			return this;
		}

		public Criteria andInsideExternalNoIsNotNull() {
			addCriterion("INSIDE_EXTERNAL_NO is not null");
			return this;
		}

		public Criteria andInsideExternalNoEqualTo(String value) {
			addCriterion("INSIDE_EXTERNAL_NO =", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoNotEqualTo(String value) {
			addCriterion("INSIDE_EXTERNAL_NO <>", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoGreaterThan(String value) {
			addCriterion("INSIDE_EXTERNAL_NO >", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoGreaterThanOrEqualTo(String value) {
			addCriterion("INSIDE_EXTERNAL_NO >=", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoLessThan(String value) {
			addCriterion("INSIDE_EXTERNAL_NO <", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoLessThanOrEqualTo(String value) {
			addCriterion("INSIDE_EXTERNAL_NO <=", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoLike(String value) {
			addCriterion("INSIDE_EXTERNAL_NO like", value, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoNotLike(String value) {
			addCriterion("INSIDE_EXTERNAL_NO not like", value,
					"insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoIn(List values) {
			addCriterion("INSIDE_EXTERNAL_NO in", values, "insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoNotIn(List values) {
			addCriterion("INSIDE_EXTERNAL_NO not in", values,
					"insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoBetween(String value1, String value2) {
			addCriterion("INSIDE_EXTERNAL_NO between", value1, value2,
					"insideExternalNo");
			return this;
		}

		public Criteria andInsideExternalNoNotBetween(String value1,
				String value2) {
			addCriterion("INSIDE_EXTERNAL_NO not between", value1, value2,
					"insideExternalNo");
			return this;
		}

		public Criteria andBookaccountTypeIsNull() {
			addCriterion("BOOKACCOUNT_TYPE is null");
			return this;
		}

		public Criteria andBookaccountTypeIsNotNull() {
			addCriterion("BOOKACCOUNT_TYPE is not null");
			return this;
		}

		public Criteria andBookaccountTypeEqualTo(String value) {
			addCriterion("BOOKACCOUNT_TYPE =", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeNotEqualTo(String value) {
			addCriterion("BOOKACCOUNT_TYPE <>", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeGreaterThan(String value) {
			addCriterion("BOOKACCOUNT_TYPE >", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeGreaterThanOrEqualTo(String value) {
			addCriterion("BOOKACCOUNT_TYPE >=", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeLessThan(String value) {
			addCriterion("BOOKACCOUNT_TYPE <", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeLessThanOrEqualTo(String value) {
			addCriterion("BOOKACCOUNT_TYPE <=", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeLike(String value) {
			addCriterion("BOOKACCOUNT_TYPE like", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeNotLike(String value) {
			addCriterion("BOOKACCOUNT_TYPE not like", value, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeIn(List values) {
			addCriterion("BOOKACCOUNT_TYPE in", values, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeNotIn(List values) {
			addCriterion("BOOKACCOUNT_TYPE not in", values, "bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeBetween(String value1, String value2) {
			addCriterion("BOOKACCOUNT_TYPE between", value1, value2,
					"bookaccountType");
			return this;
		}

		public Criteria andBookaccountTypeNotBetween(String value1,
				String value2) {
			addCriterion("BOOKACCOUNT_TYPE not between", value1, value2,
					"bookaccountType");
			return this;
		}

		public Criteria andInsideAccountNoIsNull() {
			addCriterion("INSIDE_ACCOUNT_NO is null");
			return this;
		}

		public Criteria andInsideAccountNoIsNotNull() {
			addCriterion("INSIDE_ACCOUNT_NO is not null");
			return this;
		}

		public Criteria andInsideAccountNoEqualTo(String value) {
			addCriterion("INSIDE_ACCOUNT_NO =", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoNotEqualTo(String value) {
			addCriterion("INSIDE_ACCOUNT_NO <>", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoGreaterThan(String value) {
			addCriterion("INSIDE_ACCOUNT_NO >", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoGreaterThanOrEqualTo(String value) {
			addCriterion("INSIDE_ACCOUNT_NO >=", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoLessThan(String value) {
			addCriterion("INSIDE_ACCOUNT_NO <", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoLessThanOrEqualTo(String value) {
			addCriterion("INSIDE_ACCOUNT_NO <=", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoLike(String value) {
			addCriterion("INSIDE_ACCOUNT_NO like", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoNotLike(String value) {
			addCriterion("INSIDE_ACCOUNT_NO not like", value, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoIn(List values) {
			addCriterion("INSIDE_ACCOUNT_NO in", values, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoNotIn(List values) {
			addCriterion("INSIDE_ACCOUNT_NO not in", values, "insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoBetween(String value1, String value2) {
			addCriterion("INSIDE_ACCOUNT_NO between", value1, value2,
					"insideAccountNo");
			return this;
		}

		public Criteria andInsideAccountNoNotBetween(String value1,
				String value2) {
			addCriterion("INSIDE_ACCOUNT_NO not between", value1, value2,
					"insideAccountNo");
			return this;
		}

		public Criteria andAccountSubjectIsNull() {
			addCriterion("ACCOUNT_SUBJECT is null");
			return this;
		}

		public Criteria andAccountSubjectIsNotNull() {
			addCriterion("ACCOUNT_SUBJECT is not null");
			return this;
		}

		public Criteria andAccountSubjectEqualTo(String value) {
			addCriterion("ACCOUNT_SUBJECT =", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectNotEqualTo(String value) {
			addCriterion("ACCOUNT_SUBJECT <>", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectGreaterThan(String value) {
			addCriterion("ACCOUNT_SUBJECT >", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_SUBJECT >=", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectLessThan(String value) {
			addCriterion("ACCOUNT_SUBJECT <", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_SUBJECT <=", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectLike(String value) {
			addCriterion("ACCOUNT_SUBJECT like", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectNotLike(String value) {
			addCriterion("ACCOUNT_SUBJECT not like", value, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectIn(List values) {
			addCriterion("ACCOUNT_SUBJECT in", values, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectNotIn(List values) {
			addCriterion("ACCOUNT_SUBJECT not in", values, "accountSubject");
			return this;
		}

		public Criteria andAccountSubjectBetween(String value1, String value2) {
			addCriterion("ACCOUNT_SUBJECT between", value1, value2,
					"accountSubject");
			return this;
		}

		public Criteria andAccountSubjectNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_SUBJECT not between", value1, value2,
					"accountSubject");
			return this;
		}

		public Criteria andAccountTimeIsNull() {
			addCriterion("ACCOUNT_TIME is null");
			return this;
		}

		public Criteria andAccountTimeIsNotNull() {
			addCriterion("ACCOUNT_TIME is not null");
			return this;
		}

		public Criteria andAccountTimeEqualTo(Long value) {
			addCriterion("ACCOUNT_TIME =", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeNotEqualTo(Long value) {
			addCriterion("ACCOUNT_TIME <>", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeGreaterThan(Long value) {
			addCriterion("ACCOUNT_TIME >", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("ACCOUNT_TIME >=", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeLessThan(Long value) {
			addCriterion("ACCOUNT_TIME <", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeLessThanOrEqualTo(Long value) {
			addCriterion("ACCOUNT_TIME <=", value, "accountTime");
			return this;
		}

		public Criteria andAccountTimeIn(List values) {
			addCriterion("ACCOUNT_TIME in", values, "accountTime");
			return this;
		}

		public Criteria andAccountTimeNotIn(List values) {
			addCriterion("ACCOUNT_TIME not in", values, "accountTime");
			return this;
		}

		public Criteria andAccountTimeBetween(Long value1, Long value2) {
			addCriterion("ACCOUNT_TIME between", value1, value2, "accountTime");
			return this;
		}

		public Criteria andAccountTimeNotBetween(Long value1, Long value2) {
			addCriterion("ACCOUNT_TIME not between", value1, value2,
					"accountTime");
			return this;
		}

		public Criteria andAccountMoneyIsNull() {
			addCriterion("ACCOUNT_MONEY is null");
			return this;
		}

		public Criteria andAccountMoneyIsNotNull() {
			addCriterion("ACCOUNT_MONEY is not null");
			return this;
		}

		public Criteria andAccountMoneyEqualTo(Long value) {
			addCriterion("ACCOUNT_MONEY =", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyNotEqualTo(Long value) {
			addCriterion("ACCOUNT_MONEY <>", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyGreaterThan(Long value) {
			addCriterion("ACCOUNT_MONEY >", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyGreaterThanOrEqualTo(Long value) {
			addCriterion("ACCOUNT_MONEY >=", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyLessThan(Long value) {
			addCriterion("ACCOUNT_MONEY <", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyLessThanOrEqualTo(Long value) {
			addCriterion("ACCOUNT_MONEY <=", value, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyIn(List values) {
			addCriterion("ACCOUNT_MONEY in", values, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyNotIn(List values) {
			addCriterion("ACCOUNT_MONEY not in", values, "accountMoney");
			return this;
		}

		public Criteria andAccountMoneyBetween(Long value1, Long value2) {
			addCriterion("ACCOUNT_MONEY between", value1, value2,
					"accountMoney");
			return this;
		}

		public Criteria andAccountMoneyNotBetween(Long value1, Long value2) {
			addCriterion("ACCOUNT_MONEY not between", value1, value2,
					"accountMoney");
			return this;
		}

		public Criteria andAccountDateIsNull() {
			addCriterion("ACCOUNT_DATE is null");
			return this;
		}

		public Criteria andAccountDateIsNotNull() {
			addCriterion("ACCOUNT_DATE is not null");
			return this;
		}

		public Criteria andAccountDateEqualTo(String value) {
			addCriterion("ACCOUNT_DATE =", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateNotEqualTo(String value) {
			addCriterion("ACCOUNT_DATE <>", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateGreaterThan(String value) {
			addCriterion("ACCOUNT_DATE >", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_DATE >=", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateLessThan(String value) {
			addCriterion("ACCOUNT_DATE <", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_DATE <=", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateLike(String value) {
			addCriterion("ACCOUNT_DATE like", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateNotLike(String value) {
			addCriterion("ACCOUNT_DATE not like", value, "accountDate");
			return this;
		}

		public Criteria andAccountDateIn(List values) {
			addCriterion("ACCOUNT_DATE in", values, "accountDate");
			return this;
		}

		public Criteria andAccountDateNotIn(List values) {
			addCriterion("ACCOUNT_DATE not in", values, "accountDate");
			return this;
		}

		public Criteria andAccountDateBetween(String value1, String value2) {
			addCriterion("ACCOUNT_DATE between", value1, value2, "accountDate");
			return this;
		}

		public Criteria andAccountDateNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_DATE not between", value1, value2,
					"accountDate");
			return this;
		}

		public Criteria andBookaccountStatusIsNull() {
			addCriterion("BOOKACCOUNT_STATUS is null");
			return this;
		}

		public Criteria andBookaccountStatusIsNotNull() {
			addCriterion("BOOKACCOUNT_STATUS is not null");
			return this;
		}

		public Criteria andBookaccountStatusEqualTo(String value) {
			addCriterion("BOOKACCOUNT_STATUS =", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusNotEqualTo(String value) {
			addCriterion("BOOKACCOUNT_STATUS <>", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusGreaterThan(String value) {
			addCriterion("BOOKACCOUNT_STATUS >", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusGreaterThanOrEqualTo(String value) {
			addCriterion("BOOKACCOUNT_STATUS >=", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusLessThan(String value) {
			addCriterion("BOOKACCOUNT_STATUS <", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusLessThanOrEqualTo(String value) {
			addCriterion("BOOKACCOUNT_STATUS <=", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusLike(String value) {
			addCriterion("BOOKACCOUNT_STATUS like", value, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusNotLike(String value) {
			addCriterion("BOOKACCOUNT_STATUS not like", value,
					"bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusIn(List values) {
			addCriterion("BOOKACCOUNT_STATUS in", values, "bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusNotIn(List values) {
			addCriterion("BOOKACCOUNT_STATUS not in", values,
					"bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusBetween(String value1, String value2) {
			addCriterion("BOOKACCOUNT_STATUS between", value1, value2,
					"bookaccountStatus");
			return this;
		}

		public Criteria andBookaccountStatusNotBetween(String value1,
				String value2) {
			addCriterion("BOOKACCOUNT_STATUS not between", value1, value2,
					"bookaccountStatus");
			return this;
		}

		public Criteria andTradeExternalNoIsNull() {
			addCriterion("TRADE_EXTERNAL_NO is null");
			return this;
		}

		public Criteria andTradeExternalNoIsNotNull() {
			addCriterion("TRADE_EXTERNAL_NO is not null");
			return this;
		}

		public Criteria andTradeExternalNoEqualTo(String value) {
			addCriterion("TRADE_EXTERNAL_NO =", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoNotEqualTo(String value) {
			addCriterion("TRADE_EXTERNAL_NO <>", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoGreaterThan(String value) {
			addCriterion("TRADE_EXTERNAL_NO >", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_EXTERNAL_NO >=", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoLessThan(String value) {
			addCriterion("TRADE_EXTERNAL_NO <", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoLessThanOrEqualTo(String value) {
			addCriterion("TRADE_EXTERNAL_NO <=", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoLike(String value) {
			addCriterion("TRADE_EXTERNAL_NO like", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoNotLike(String value) {
			addCriterion("TRADE_EXTERNAL_NO not like", value, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoIn(List values) {
			addCriterion("TRADE_EXTERNAL_NO in", values, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoNotIn(List values) {
			addCriterion("TRADE_EXTERNAL_NO not in", values, "tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoBetween(String value1, String value2) {
			addCriterion("TRADE_EXTERNAL_NO between", value1, value2,
					"tradeExternalNo");
			return this;
		}

		public Criteria andTradeExternalNoNotBetween(String value1,
				String value2) {
			addCriterion("TRADE_EXTERNAL_NO not between", value1, value2,
					"tradeExternalNo");
			return this;
		}

		public Criteria andExternalAccountChannelIsNull() {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL is null");
			return this;
		}

		public Criteria andExternalAccountChannelIsNotNull() {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL is not null");
			return this;
		}

		public Criteria andExternalAccountChannelEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL =", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelNotEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL <>", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelGreaterThan(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL >", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelGreaterThanOrEqualTo(
				String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL >=", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelLessThan(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL <", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelLessThanOrEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL <=", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelLike(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL like", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelNotLike(String value) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL not like", value,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelIn(List values) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL in", values,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelNotIn(List values) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL not in", values,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelBetween(String value1,
				String value2) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL between", value1, value2,
					"externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountChannelNotBetween(String value1,
				String value2) {
			addCriterion("EXTERNAL_ACCOUNT_CHANNEL not between", value1,
					value2, "externalAccountChannel");
			return this;
		}

		public Criteria andExternalAccountNoIsNull() {
			addCriterion("EXTERNAL_ACCOUNT_NO is null");
			return this;
		}

		public Criteria andExternalAccountNoIsNotNull() {
			addCriterion("EXTERNAL_ACCOUNT_NO is not null");
			return this;
		}

		public Criteria andExternalAccountNoEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO =", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoNotEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO <>", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoGreaterThan(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO >", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoGreaterThanOrEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO >=", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoLessThan(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO <", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoLessThanOrEqualTo(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO <=", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoLike(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO like", value, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoNotLike(String value) {
			addCriterion("EXTERNAL_ACCOUNT_NO not like", value,
					"externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoIn(List values) {
			addCriterion("EXTERNAL_ACCOUNT_NO in", values, "externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoNotIn(List values) {
			addCriterion("EXTERNAL_ACCOUNT_NO not in", values,
					"externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoBetween(String value1, String value2) {
			addCriterion("EXTERNAL_ACCOUNT_NO between", value1, value2,
					"externalAccountNo");
			return this;
		}

		public Criteria andExternalAccountNoNotBetween(String value1,
				String value2) {
			addCriterion("EXTERNAL_ACCOUNT_NO not between", value1, value2,
					"externalAccountNo");
			return this;
		}

		public Criteria andSubAccountIdIsNull() {
			addCriterion("SUB_ACCOUNT_ID is null");
			return this;
		}

		public Criteria andSubAccountIdIsNotNull() {
			addCriterion("SUB_ACCOUNT_ID is not null");
			return this;
		}

		public Criteria andSubAccountIdEqualTo(String value) {
			addCriterion("SUB_ACCOUNT_ID =", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdNotEqualTo(String value) {
			addCriterion("SUB_ACCOUNT_ID <>", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdGreaterThan(String value) {
			addCriterion("SUB_ACCOUNT_ID >", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdGreaterThanOrEqualTo(String value) {
			addCriterion("SUB_ACCOUNT_ID >=", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdLessThan(String value) {
			addCriterion("SUB_ACCOUNT_ID <", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdLessThanOrEqualTo(String value) {
			addCriterion("SUB_ACCOUNT_ID <=", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdLike(String value) {
			addCriterion("SUB_ACCOUNT_ID like", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdNotLike(String value) {
			addCriterion("SUB_ACCOUNT_ID not like", value, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdIn(List values) {
			addCriterion("SUB_ACCOUNT_ID in", values, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdNotIn(List values) {
			addCriterion("SUB_ACCOUNT_ID not in", values, "subAccountId");
			return this;
		}

		public Criteria andSubAccountIdBetween(String value1, String value2) {
			addCriterion("SUB_ACCOUNT_ID between", value1, value2,
					"subAccountId");
			return this;
		}

		public Criteria andSubAccountIdNotBetween(String value1, String value2) {
			addCriterion("SUB_ACCOUNT_ID not between", value1, value2,
					"subAccountId");
			return this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("ACCOUNT_ID is null");
			return this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("ACCOUNT_ID is not null");
			return this;
		}

		public Criteria andAccountIdEqualTo(String value) {
			addCriterion("ACCOUNT_ID =", value, "accountId");
			return this;
		}

		public Criteria andAccountIdNotEqualTo(String value) {
			addCriterion("ACCOUNT_ID <>", value, "accountId");
			return this;
		}

		public Criteria andAccountIdGreaterThan(String value) {
			addCriterion("ACCOUNT_ID >", value, "accountId");
			return this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_ID >=", value, "accountId");
			return this;
		}

		public Criteria andAccountIdLessThan(String value) {
			addCriterion("ACCOUNT_ID <", value, "accountId");
			return this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_ID <=", value, "accountId");
			return this;
		}

		public Criteria andAccountIdLike(String value) {
			addCriterion("ACCOUNT_ID like", value, "accountId");
			return this;
		}

		public Criteria andAccountIdNotLike(String value) {
			addCriterion("ACCOUNT_ID not like", value, "accountId");
			return this;
		}

		public Criteria andAccountIdIn(List values) {
			addCriterion("ACCOUNT_ID in", values, "accountId");
			return this;
		}

		public Criteria andAccountIdNotIn(List values) {
			addCriterion("ACCOUNT_ID not in", values, "accountId");
			return this;
		}

		public Criteria andAccountIdBetween(String value1, String value2) {
			addCriterion("ACCOUNT_ID between", value1, value2, "accountId");
			return this;
		}

		public Criteria andAccountIdNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_ID not between", value1, value2, "accountId");
			return this;
		}

		public Criteria andOperatorIdIsNull() {
			addCriterion("OPERATOR_ID is null");
			return this;
		}

		public Criteria andOperatorIdIsNotNull() {
			addCriterion("OPERATOR_ID is not null");
			return this;
		}

		public Criteria andOperatorIdEqualTo(String value) {
			addCriterion("OPERATOR_ID =", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdNotEqualTo(String value) {
			addCriterion("OPERATOR_ID <>", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdGreaterThan(String value) {
			addCriterion("OPERATOR_ID >", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID >=", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdLessThan(String value) {
			addCriterion("OPERATOR_ID <", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID <=", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdLike(String value) {
			addCriterion("OPERATOR_ID like", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdNotLike(String value) {
			addCriterion("OPERATOR_ID not like", value, "operatorId");
			return this;
		}

		public Criteria andOperatorIdIn(List values) {
			addCriterion("OPERATOR_ID in", values, "operatorId");
			return this;
		}

		public Criteria andOperatorIdNotIn(List values) {
			addCriterion("OPERATOR_ID not in", values, "operatorId");
			return this;
		}

		public Criteria andOperatorIdBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID between", value1, value2, "operatorId");
			return this;
		}

		public Criteria andOperatorIdNotBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID not between", value1, value2,
					"operatorId");
			return this;
		}

		public Criteria andBookAccountInfoIdIsNull() {
			addCriterion("BOOK_ACCOUNT_INFO_ID is null");
			return this;
		}

		public Criteria andBookAccountInfoIdIsNotNull() {
			addCriterion("BOOK_ACCOUNT_INFO_ID is not null");
			return this;
		}

		public Criteria andBookAccountInfoIdEqualTo(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID =", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdNotEqualTo(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID <>", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdGreaterThan(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID >", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdGreaterThanOrEqualTo(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID >=", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdLessThan(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID <", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdLessThanOrEqualTo(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID <=", value, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdLike(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID like", value,
					"bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdNotLike(String value) {
			addCriterion("BOOK_ACCOUNT_INFO_ID not like", value,
					"bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdIn(List values) {
			addCriterion("BOOK_ACCOUNT_INFO_ID in", values, "bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdNotIn(List values) {
			addCriterion("BOOK_ACCOUNT_INFO_ID not in", values,
					"bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdBetween(String value1, String value2) {
			addCriterion("BOOK_ACCOUNT_INFO_ID between", value1, value2,
					"bookAccountInfoId");
			return this;
		}

		public Criteria andBookAccountInfoIdNotBetween(String value1,
				String value2) {
			addCriterion("BOOK_ACCOUNT_INFO_ID not between", value1, value2,
					"bookAccountInfoId");
			return this;
		}

		public Criteria andAccountSubareaTimeIsNull() {
			addCriterion("ACCOUNT_SUBAREA_TIME is null");
			return this;
		}

		public Criteria andAccountSubareaTimeIsNotNull() {
			addCriterion("ACCOUNT_SUBAREA_TIME is not null");
			return this;
		}

		public Criteria andAccountSubareaTimeEqualTo(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME =", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeNotEqualTo(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME <>", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeGreaterThan(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME >", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME >=", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeLessThan(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME <", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeLessThanOrEqualTo(Date value) {
			addCriterion("ACCOUNT_SUBAREA_TIME <=", value, "accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeIn(List values) {
			addCriterion("ACCOUNT_SUBAREA_TIME in", values,
					"accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeNotIn(List values) {
			addCriterion("ACCOUNT_SUBAREA_TIME not in", values,
					"accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeBetween(Date value1, Date value2) {
			addCriterion("ACCOUNT_SUBAREA_TIME between", value1, value2,
					"accountSubareaTime");
			return this;
		}

		public Criteria andAccountSubareaTimeNotBetween(Date value1, Date value2) {
			addCriterion("ACCOUNT_SUBAREA_TIME not between", value1, value2,
					"accountSubareaTime");
			return this;
		}

		public Criteria andStoreCodeIsNull() {
			addCriterion("STORE_CODE is null");
			return this;
		}

		public Criteria andStoreCodeIsNotNull() {
			addCriterion("STORE_CODE is not null");
			return this;
		}

		public Criteria andStoreCodeEqualTo(String value) {
			addCriterion("STORE_CODE =", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeNotEqualTo(String value) {
			addCriterion("STORE_CODE <>", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeGreaterThan(String value) {
			addCriterion("STORE_CODE >", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeGreaterThanOrEqualTo(String value) {
			addCriterion("STORE_CODE >=", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeLessThan(String value) {
			addCriterion("STORE_CODE <", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeLessThanOrEqualTo(String value) {
			addCriterion("STORE_CODE <=", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeLike(String value) {
			addCriterion("STORE_CODE like", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeNotLike(String value) {
			addCriterion("STORE_CODE not like", value, "storeCode");
			return this;
		}

		public Criteria andStoreCodeIn(List values) {
			addCriterion("STORE_CODE in", values, "storeCode");
			return this;
		}

		public Criteria andStoreCodeNotIn(List values) {
			addCriterion("STORE_CODE not in", values, "storeCode");
			return this;
		}

		public Criteria andStoreCodeBetween(String value1, String value2) {
			addCriterion("STORE_CODE between", value1, value2, "storeCode");
			return this;
		}

		public Criteria andStoreCodeNotBetween(String value1, String value2) {
			addCriterion("STORE_CODE not between", value1, value2, "storeCode");
			return this;
		}

		public Criteria andCurrentMoneyIsNull() {
			addCriterion("CURRENT_MONEY is null");
			return this;
		}

		public Criteria andCurrentMoneyIsNotNull() {
			addCriterion("CURRENT_MONEY is not null");
			return this;
		}

		public Criteria andCurrentMoneyEqualTo(Long value) {
			addCriterion("CURRENT_MONEY =", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyNotEqualTo(Long value) {
			addCriterion("CURRENT_MONEY <>", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyGreaterThan(Long value) {
			addCriterion("CURRENT_MONEY >", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyGreaterThanOrEqualTo(Long value) {
			addCriterion("CURRENT_MONEY >=", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyLessThan(Long value) {
			addCriterion("CURRENT_MONEY <", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyLessThanOrEqualTo(Long value) {
			addCriterion("CURRENT_MONEY <=", value, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyIn(List values) {
			addCriterion("CURRENT_MONEY in", values, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyNotIn(List values) {
			addCriterion("CURRENT_MONEY not in", values, "currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyBetween(Long value1, Long value2) {
			addCriterion("CURRENT_MONEY between", value1, value2,
					"currentMoney");
			return this;
		}

		public Criteria andCurrentMoneyNotBetween(Long value1, Long value2) {
			addCriterion("CURRENT_MONEY not between", value1, value2,
					"currentMoney");
			return this;
		}
	}
}