package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.Image;
import com.sinoiov.vehicle.dao.beans.ImageExample;
import com.sinoiov.vehicle.dao.beans.ImageExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ImageDAOImpl extends SqlMapClientDaoSupport implements ImageDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public ImageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void insert(Image record) {
		getSqlMapClientTemplate().insert("TB_IMAGE.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKeyWithoutBLOBs(Image record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKeyWithBLOBs(Image record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKeySelective(Image record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithoutBLOBs(ImageExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithBLOBs(ImageExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectByExampleWithBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public Image selectByPrimaryKey(String id) {
		Image key = new Image() {
		};
		key.setId(id);
		Image record = (Image) getSqlMapClientTemplate().queryForObject(
				"TB_IMAGE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByExample(ImageExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IMAGE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByPrimaryKey(String id) {
		Image key = new Image() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IMAGE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(ImageExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IMAGE.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExampleSelective(Image record, ImageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExampleWithBLOBs(Image record, ImageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExampleWithoutBLOBs(Image record, ImageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IMAGE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPageWithoutBLOBs(ImageExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPageWithoutBLOBs(
			ImageExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(ImageExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getNameSpace() {
		return "TB_IMAGE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(ImageExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IMAGE.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(ImageExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IMAGE.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IMAGE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	private static class UpdateByExampleParms extends ImageExample {
		private Object record;

		public UpdateByExampleParms(Object record, ImageExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}