package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.LoadTime;
import com.sinoiov.vehicle.dao.beans.LoadTimeExample;
import com.sinoiov.vehicle.dao.beans.LoadTimeExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LoadTimeDAOImpl extends SqlMapClientDaoSupport implements LoadTimeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public LoadTimeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public void insert(LoadTime record) {
		getSqlMapClientTemplate().insert("TB_LOAD_TIME.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByPrimaryKey(LoadTime record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_LOAD_TIME.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByPrimaryKeySelective(LoadTime record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_LOAD_TIME.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExample(LoadTimeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_LOAD_TIME.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public LoadTime selectByPrimaryKey(Integer id) {
		LoadTime key = new LoadTime() {
		};
		key.setId(id);
		LoadTime record = (LoadTime) getSqlMapClientTemplate().queryForObject(
				"TB_LOAD_TIME.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int deleteByExample(LoadTimeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_LOAD_TIME.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int deleteByPrimaryKey(Integer id) {
		LoadTime key = new LoadTime() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_LOAD_TIME.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int countByExample(LoadTimeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_LOAD_TIME.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByExampleSelective(LoadTime record, LoadTimeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_LOAD_TIME.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByExample(LoadTime record, LoadTimeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_LOAD_TIME.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExampleWithPage(LoadTimeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_LOAD_TIME.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExampleWithPage(LoadTimeExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_LOAD_TIME.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List getKeyBy(LoadTimeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_LOAD_TIME.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public String getNameSpace() {
		return "TB_LOAD_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List getKeyBy(LoadTimeExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_LOAD_TIME.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int countByExample(LoadTimeExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_LOAD_TIME.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_LOAD_TIME
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	private static class UpdateByExampleParms extends LoadTimeExample {
		private Object record;

		public UpdateByExampleParms(Object record, LoadTimeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}