package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.VehicleAuthentication;
import com.sinoiov.vehicle.dao.beans.VehicleAuthenticationExample;
import com.sinoiov.vehicle.dao.beans.VehicleAuthenticationExampleExtended;
import java.util.List;

public interface VehicleAuthenticationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    void insert(VehicleAuthentication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int updateByPrimaryKey(VehicleAuthentication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int updateByPrimaryKeySelective(VehicleAuthentication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    List selectByExample(VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    VehicleAuthentication selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int deleteByExample(VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int countByExample(VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int updateByExampleSelective(VehicleAuthentication record, VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int updateByExample(VehicleAuthentication record, VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    List selectByExampleWithPage(VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    List selectByExampleWithPage(VehicleAuthenticationExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    List getKeyBy(VehicleAuthenticationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    List getKeyBy(VehicleAuthenticationExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    int countByExample(VehicleAuthenticationExampleExtended example);
}