package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.VehicleAuthentication;
import com.sinoiov.vehicle.dao.beans.VehicleAuthenticationExample;
import com.sinoiov.vehicle.dao.beans.VehicleAuthenticationExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VehicleAuthenticationDAOImpl extends SqlMapClientDaoSupport implements VehicleAuthenticationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public VehicleAuthenticationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public void insert(VehicleAuthentication record) {
        getSqlMapClientTemplate().insert("TB_VEHICLE_AUTHENTICATION.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int updateByPrimaryKey(VehicleAuthentication record) {
        int rows = getSqlMapClientTemplate().update("TB_VEHICLE_AUTHENTICATION.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int updateByPrimaryKeySelective(VehicleAuthentication record) {
        int rows = getSqlMapClientTemplate().update("TB_VEHICLE_AUTHENTICATION.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public List selectByExample(VehicleAuthenticationExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public VehicleAuthentication selectByPrimaryKey(String id) {
        VehicleAuthentication key = new VehicleAuthentication(){};
        key.setId(id);
        VehicleAuthentication record = (VehicleAuthentication) getSqlMapClientTemplate().queryForObject("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int deleteByExample(VehicleAuthenticationExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_VEHICLE_AUTHENTICATION.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int deleteByPrimaryKey(String id) {
        VehicleAuthentication key = new VehicleAuthentication(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_VEHICLE_AUTHENTICATION.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int countByExample(VehicleAuthenticationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_VEHICLE_AUTHENTICATION.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int updateByExampleSelective(VehicleAuthentication record, VehicleAuthenticationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_VEHICLE_AUTHENTICATION.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int updateByExample(VehicleAuthentication record, VehicleAuthenticationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_VEHICLE_AUTHENTICATION.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public List selectByExampleWithPage(VehicleAuthenticationExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public List selectByExampleWithPage(VehicleAuthenticationExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public List getKeyBy(VehicleAuthenticationExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public String getNameSpace() {
         return "TB_VEHICLE_AUTHENTICATION";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public List getKeyBy(VehicleAuthenticationExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_VEHICLE_AUTHENTICATION.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    public int countByExample(VehicleAuthenticationExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_VEHICLE_AUTHENTICATION.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TB_VEHICLE_AUTHENTICATION
     *
     * @abatorgenerated Mon Jan 11 19:46:59 CST 2016
     */
    private static class UpdateByExampleParms extends VehicleAuthenticationExample {
        private Object record;

        public UpdateByExampleParms(Object record, VehicleAuthenticationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}