package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.VehicleLine;
import com.sinoiov.vehicle.dao.beans.VehicleLineExample;
import com.sinoiov.vehicle.dao.beans.VehicleLineExampleExtended;
import java.util.List;

public interface VehicleLineDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	void insert(VehicleLine record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByPrimaryKey(VehicleLine record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByPrimaryKeySelective(VehicleLine record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExample(VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	VehicleLine selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int deleteByExample(VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int countByExample(VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByExampleSelective(VehicleLine record, VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByExample(VehicleLine record, VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExampleWithPage(VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExampleWithPage(VehicleLineExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List getKeyBy(VehicleLineExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List getKeyBy(VehicleLineExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int countByExample(VehicleLineExampleExtended example);
}