package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.VehicleLable;
import com.sinoiov.vehicle.dao.beans.VehicleLableExample;
import com.sinoiov.vehicle.dao.beans.VehicleLableExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VehicleLableDAOImpl extends SqlMapClientDaoSupport implements VehicleLableDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLableDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void insert(VehicleLable record) {
		getSqlMapClientTemplate().insert(
				"TB_VEHICLE_LABLE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKey(VehicleLable record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LABLE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKeySelective(VehicleLable record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LABLE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExample(VehicleLableExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LABLE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLable selectByPrimaryKey(String id) {
		VehicleLable key = new VehicleLable() {
		};
		key.setId(id);
		VehicleLable record = (VehicleLable) getSqlMapClientTemplate()
				.queryForObject(
						"TB_VEHICLE_LABLE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByExample(VehicleLableExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE_LABLE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByPrimaryKey(String id) {
		VehicleLable key = new VehicleLable() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE_LABLE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(VehicleLableExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE_LABLE.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExampleSelective(VehicleLable record,
			VehicleLableExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LABLE.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExample(VehicleLable record, VehicleLableExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LABLE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPage(VehicleLableExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_VEHICLE_LABLE.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPage(
			VehicleLableExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LABLE.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(VehicleLableExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LABLE.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getNameSpace() {
		return "TB_VEHICLE_LABLE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(VehicleLableExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_VEHICLE_LABLE.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(VehicleLableExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE_LABLE.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_VEHICLE_LABLE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	private static class UpdateByExampleParms extends VehicleLableExample {
		private Object record;

		public UpdateByExampleParms(Object record, VehicleLableExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}