package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.Vehicle;
import com.sinoiov.vehicle.dao.beans.VehicleExample;
import com.sinoiov.vehicle.dao.beans.VehicleExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VehicleDAOImpl extends SqlMapClientDaoSupport implements VehicleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public VehicleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public void insert(Vehicle record) {
		getSqlMapClientTemplate().insert("TB_VEHICLE.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByPrimaryKey(Vehicle record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByPrimaryKeySelective(Vehicle record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExample(VehicleExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public Vehicle selectByPrimaryKey(String id) {
		Vehicle key = new Vehicle() {
		};
		key.setId(id);
		Vehicle record = (Vehicle) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int deleteByExample(VehicleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int deleteByPrimaryKey(String id) {
		Vehicle key = new Vehicle() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int countByExample(VehicleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByExampleSelective(Vehicle record, VehicleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int updateByExample(Vehicle record, VehicleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExampleWithPage(VehicleExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List selectByExampleWithPage(VehicleExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List getKeyBy(VehicleExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public String getNameSpace() {
		return "TB_VEHICLE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public List getKeyBy(VehicleExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	public int countByExample(VehicleExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_VEHICLE
	 * @abatorgenerated  Sun Jan 10 19:24:12 CST 2016
	 */
	private static class UpdateByExampleParms extends VehicleExample {
		private Object record;

		public UpdateByExampleParms(Object record, VehicleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}