package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.VehicleLine;
import com.sinoiov.vehicle.dao.beans.VehicleLineExample;
import com.sinoiov.vehicle.dao.beans.VehicleLineExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VehicleLineDAOImpl extends SqlMapClientDaoSupport implements VehicleLineDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLineDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public void insert(VehicleLine record) {
		getSqlMapClientTemplate().insert(
				"TB_VEHICLE_LINE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKey(VehicleLine record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LINE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByPrimaryKeySelective(VehicleLine record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LINE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExample(VehicleLineExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LINE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public VehicleLine selectByPrimaryKey(String id) {
		VehicleLine key = new VehicleLine() {
		};
		key.setId(id);
		VehicleLine record = (VehicleLine) getSqlMapClientTemplate()
				.queryForObject(
						"TB_VEHICLE_LINE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByExample(VehicleLineExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE_LINE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int deleteByPrimaryKey(String id) {
		VehicleLine key = new VehicleLine() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_VEHICLE_LINE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(VehicleLineExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE_LINE.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExampleSelective(VehicleLine record,
			VehicleLineExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LINE.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int updateByExample(VehicleLine record, VehicleLineExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VEHICLE_LINE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPage(VehicleLineExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LINE.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List selectByExampleWithPage(
			VehicleLineExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LINE.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(VehicleLineExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LINE.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public String getNameSpace() {
		return "TB_VEHICLE_LINE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public List getKeyBy(VehicleLineExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_VEHICLE_LINE.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	public int countByExample(VehicleLineExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VEHICLE_LINE.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_VEHICLE_LINE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	private static class UpdateByExampleParms extends VehicleLineExample {
		private Object record;

		public UpdateByExampleParms(Object record, VehicleLineExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}