package com.sinoiov.vehicle.dao;

import com.sinoiov.vehicle.dao.beans.ZoneCode;
import com.sinoiov.vehicle.dao.beans.ZoneCodeExample;
import com.sinoiov.vehicle.dao.beans.ZoneCodeExampleExtended;
import java.util.List;

public interface ZoneCodeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	void insert(ZoneCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByPrimaryKey(ZoneCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByPrimaryKeySelective(ZoneCode record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExample(ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	ZoneCode selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int deleteByExample(ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int countByExample(ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByExampleSelective(ZoneCode record, ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int updateByExample(ZoneCode record, ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExampleWithPage(ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List selectByExampleWithPage(ZoneCodeExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List getKeyBy(ZoneCodeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	List getKeyBy(ZoneCodeExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_ZONE_CODE
	 * @abatorgenerated  Mon Jan 11 19:46:59 CST 2016
	 */
	int countByExample(ZoneCodeExampleExtended example);
}