package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AccountSafetyMess;
import com.ctfo.account.dao.beans.AccountSafetyMessExample;
import com.ctfo.account.dao.beans.AccountSafetyMessExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccountSafetyMessDAOImpl extends SqlMapClientDaoSupport implements AccountSafetyMessDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public AccountSafetyMessDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public void insert(AccountSafetyMess record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int updateByPrimaryKey(AccountSafetyMess record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int updateByPrimaryKeySelective(AccountSafetyMess record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public List selectByExample(AccountSafetyMessExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public AccountSafetyMess selectByPrimaryKey(String id) {
		AccountSafetyMess key = new AccountSafetyMess() {
		};
		key.setId(id);
		AccountSafetyMess record = (AccountSafetyMess) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int deleteByExample(AccountSafetyMessExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		AccountSafetyMess key = new AccountSafetyMess() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int countByExample(AccountSafetyMessExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int updateByExampleSelective(AccountSafetyMess record,
			AccountSafetyMessExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int updateByExample(AccountSafetyMess record,
			AccountSafetyMessExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public List selectByExampleWithPage(AccountSafetyMessExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public List selectByExampleWithPage(
			AccountSafetyMessExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public List getKeyBy(AccountSafetyMessExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_ACCOUNT_SAFETY_MESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public List getKeyBy(AccountSafetyMessExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	public int countByExample(AccountSafetyMessExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_ACCOUNT_SAFETY_MESS.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	private static class UpdateByExampleParms extends AccountSafetyMessExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				AccountSafetyMessExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}