package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AccountDetail;
import com.ctfo.account.dao.beans.AccountDetailExample;
import com.ctfo.account.dao.beans.AccountDetailExampleExtended;
import java.util.List;

public interface AccountDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	void insert(AccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int updateByPrimaryKey(AccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int updateByPrimaryKeySelective(AccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	List selectByExample(AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	AccountDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int deleteByExample(AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int countByExample(AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int updateByExampleSelective(AccountDetail record,
			AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int updateByExample(AccountDetail record, AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	List selectByExampleWithPage(AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	List selectByExampleWithPage(AccountDetailExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	List getKeyBy(AccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	List getKeyBy(AccountDetailExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	int countByExample(AccountDetailExampleExtended example);
}