package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AccountDetail;
import com.ctfo.account.dao.beans.AccountDetailExample;
import com.ctfo.account.dao.beans.AccountDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccountDetailDAOImpl extends SqlMapClientDaoSupport implements AccountDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public AccountDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public void insert(AccountDetail record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int updateByPrimaryKey(AccountDetail record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int updateByPrimaryKeySelective(AccountDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public List selectByExample(AccountDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public AccountDetail selectByPrimaryKey(String id) {
		AccountDetail key = new AccountDetail() {
		};
		key.setId(id);
		AccountDetail record = (AccountDetail) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int deleteByExample(AccountDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		AccountDetail key = new AccountDetail() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int countByExample(AccountDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int updateByExampleSelective(AccountDetail record,
			AccountDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int updateByExample(AccountDetail record,
			AccountDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public List selectByExampleWithPage(AccountDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public List selectByExampleWithPage(
			AccountDetailExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public List getKeyBy(AccountDetailExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectKeyBy",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_BOOK_ACCOUNT_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public List getKeyBy(AccountDetailExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	public int countByExample(AccountDetailExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_BOOK_ACCOUNT_INFO.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri May 29 16:52:46 CST 2015
	 */
	private static class UpdateByExampleParms extends AccountDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record, AccountDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}