package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.payment.dao.beans.AccountingMonth;
import com.ctfo.payment.dao.beans.AccountingMonthExample;
import com.ctfo.payment.dao.beans.AccountingMonthExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccountingMonthDAOImpl extends SqlMapClientDaoSupport implements AccountingMonthDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public AccountingMonthDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public void insert(AccountingMonth record) {
        getSqlMapClientTemplate().insert("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int updateByPrimaryKey(AccountingMonth record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int updateByPrimaryKeySelective(AccountingMonth record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public List selectByExample(AccountingMonthExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public AccountingMonth selectByPrimaryKey(String id) {
        AccountingMonth key = new AccountingMonth(){};
        key.setId(id);
        AccountingMonth record = (AccountingMonth) getSqlMapClientTemplate().queryForObject("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int deleteByExample(AccountingMonthExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        AccountingMonth key = new AccountingMonth(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int countByExample(AccountingMonthExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int updateByExampleSelective(AccountingMonth record, AccountingMonthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int updateByExample(AccountingMonth record, AccountingMonthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public List selectByExampleWithPage(AccountingMonthExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public List selectByExampleWithPage(AccountingMonthExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public List getKeyBy(AccountingMonthExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public String getNameSpace() {
         return "TB_UPP_BOOK_MONTH_ACCOUNT";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public List getKeyBy(AccountingMonthExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    public int countByExample(AccountingMonthExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_BOOK_MONTH_ACCOUNT.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_BOOK_MONTH_ACCOUNT
     *
     * @abatorgenerated Thu Mar 19 09:14:44 CST 2015
     */
    private static class UpdateByExampleParms extends AccountingMonthExample {
        private Object record;

        public UpdateByExampleParms(Object record, AccountingMonthExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}