package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AccountSafetyMess;
import com.ctfo.account.dao.beans.AccountSafetyMessExample;
import com.ctfo.account.dao.beans.AccountSafetyMessExampleExtended;
import java.util.List;

public interface AccountSafetyMessDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	void insert(AccountSafetyMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int updateByPrimaryKey(AccountSafetyMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int updateByPrimaryKeySelective(AccountSafetyMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	List selectByExample(AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	AccountSafetyMess selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int deleteByExample(AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int countByExample(AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int updateByExampleSelective(AccountSafetyMess record,
			AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int updateByExample(AccountSafetyMess record,
			AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	List selectByExampleWithPage(AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	List selectByExampleWithPage(
			AccountSafetyMessExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	List getKeyBy(AccountSafetyMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	List getKeyBy(AccountSafetyMessExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_ACCOUNT_SAFETY_MESS
	 * @abatorgenerated  Mon Jun 01 19:19:24 CST 2015
	 */
	int countByExample(AccountSafetyMessExampleExtended example);
}