package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.payment.dao.beans.AccountingDay;
import com.ctfo.payment.dao.beans.AccountingDayExample;
import com.ctfo.payment.dao.beans.AccountingDayExampleExtended;
import java.util.List;

public interface AccountingDayDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	void insert(AccountingDay record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int updateByPrimaryKey(AccountingDay record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int updateByPrimaryKeySelective(AccountingDay record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	List selectByExample(AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	AccountingDay selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int deleteByExample(AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int countByExample(AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int updateByExampleSelective(AccountingDay record,
			AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int updateByExample(AccountingDay record, AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	List selectByExampleWithPage(AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	List selectByExampleWithPage(AccountingDayExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	List getKeyBy(AccountingDayExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	List getKeyBy(AccountingDayExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_BOOK_DAY_ACCOUNT
	 * @abatorgenerated  Tue Apr 07 14:19:09 CST 2015
	 */
	int countByExample(AccountingDayExampleExtended example);
}