package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.Account;
import com.ctfo.account.dao.beans.AccountExample;
import com.ctfo.account.dao.beans.AccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AccountDAOImpl extends SqlMapClientDaoSupport implements AccountDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public AccountDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public void insert(Account record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int updateByPrimaryKey(Account record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int updateByPrimaryKeySelective(Account record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CASH_ACCOUNT.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public List selectByExample(AccountExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public Account selectByPrimaryKey(String id) {
		Account key = new Account() {
		};
		key.setId(id);
		Account record = (Account) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int deleteByExample(AccountExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		Account key = new Account() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int countByExample(AccountExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int updateByExampleSelective(Account record, AccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int updateByExample(Account record, AccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public List selectByExampleWithPage(AccountExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public List selectByExampleWithPage(AccountExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public List getKeyBy(AccountExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_CASH_ACCOUNT";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public List getKeyBy(AccountExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	public int countByExample(AccountExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_CASH_ACCOUNT.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT
	 * @abatorgenerated  Mon Jul 20 18:50:28 CST 2015
	 */
	private static class UpdateByExampleParms extends AccountExample {
		private Object record;

		public UpdateByExampleParms(Object record, AccountExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}