package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AuthenApplyInfo;
import com.ctfo.account.dao.beans.AuthenApplyInfoExample;
import com.ctfo.account.dao.beans.AuthenApplyInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AuthenApplyInfoDAOImpl extends SqlMapClientDaoSupport implements AuthenApplyInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public AuthenApplyInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public void insert(AuthenApplyInfo record) {
		getSqlMapClientTemplate().insert("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int updateByPrimaryKey(AuthenApplyInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int updateByPrimaryKeySelective(AuthenApplyInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public List selectByExample(AuthenApplyInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public AuthenApplyInfo selectByPrimaryKey(String id) {
		AuthenApplyInfo key = new AuthenApplyInfo() {
		};
		key.setId(id);
		AuthenApplyInfo record = (AuthenApplyInfo) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int deleteByExample(AuthenApplyInfoExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		AuthenApplyInfo key = new AuthenApplyInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int countByExample(AuthenApplyInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int updateByExampleSelective(AuthenApplyInfo record, AuthenApplyInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int updateByExample(AuthenApplyInfo record, AuthenApplyInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public List selectByExampleWithPage(AuthenApplyInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public List selectByExampleWithPage(AuthenApplyInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public List getKeyBy(AuthenApplyInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_AUTHENTICA_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public List getKeyBy(AuthenApplyInfoExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	public int countByExample(AuthenApplyInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_APPLY.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	private static class UpdateByExampleParms extends AuthenApplyInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, AuthenApplyInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}