package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.AuthenApplyInfo;
import com.ctfo.account.dao.beans.AuthenApplyInfoExample;
import com.ctfo.account.dao.beans.AuthenApplyInfoExampleExtended;
import java.util.List;

public interface AuthenApplyInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	void insert(AuthenApplyInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int updateByPrimaryKey(AuthenApplyInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int updateByPrimaryKeySelective(AuthenApplyInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	List selectByExample(AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	AuthenApplyInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int deleteByExample(AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int countByExample(AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int updateByExampleSelective(AuthenApplyInfo record, AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int updateByExample(AuthenApplyInfo record, AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	List selectByExampleWithPage(AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	List selectByExampleWithPage(AuthenApplyInfoExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	List getKeyBy(AuthenApplyInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	List getKeyBy(AuthenApplyInfoExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_APPLY
	 * @abatorgenerated  Tue Dec 23 09:53:22 CST 2014
	 */
	int countByExample(AuthenApplyInfoExampleExtended example);
}