package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.CertifiedInfo;
import com.ctfo.account.dao.beans.CertifiedInfoExample;
import com.ctfo.account.dao.beans.CertifiedInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CertifiedInfoDAOImpl extends SqlMapClientDaoSupport implements CertifiedInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public CertifiedInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public void insert(CertifiedInfo record) {
		getSqlMapClientTemplate().insert("TB_UPP_AUTHENTICA_MESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int updateByPrimaryKey(CertifiedInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_MESS.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int updateByPrimaryKeySelective(CertifiedInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_MESS.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public List selectByExample(CertifiedInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public CertifiedInfo selectByPrimaryKey(String id) {
		CertifiedInfo key = new CertifiedInfo() {
		};
		key.setId(id);
		CertifiedInfo record = (CertifiedInfo) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int deleteByExample(CertifiedInfoExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_UPP_AUTHENTICA_MESS.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		CertifiedInfo key = new CertifiedInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("TB_UPP_AUTHENTICA_MESS.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int countByExample(CertifiedInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_MESS.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int updateByExampleSelective(CertifiedInfo record, CertifiedInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_MESS.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int updateByExample(CertifiedInfo record, CertifiedInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_AUTHENTICA_MESS.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public List selectByExampleWithPage(CertifiedInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public List selectByExampleWithPage(CertifiedInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public List getKeyBy(CertifiedInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_AUTHENTICA_MESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public List getKeyBy(CertifiedInfoExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_AUTHENTICA_MESS.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	public int countByExample(CertifiedInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_AUTHENTICA_MESS.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_AUTHENTICA_MESS
	 * @abatorgenerated  Tue Nov 11 14:16:54 CST 2014
	 */
	private static class UpdateByExampleParms extends CertifiedInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, CertifiedInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}