package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.DetailWithThirdPartyAccount;
import com.ctfo.account.dao.beans.DetailWithThirdPartyAccountExample;
import com.ctfo.account.dao.beans.DetailWithThirdPartyAccountExampleExtended;
import java.util.List;

public interface DetailWithThirdPartyAccountDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    void insert(DetailWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int updateByPrimaryKey(DetailWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int updateByPrimaryKeySelective(DetailWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    List selectByExample(DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    DetailWithThirdPartyAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int deleteByExample(DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int countByExample(DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int updateByExampleSelective(DetailWithThirdPartyAccount record, DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int updateByExample(DetailWithThirdPartyAccount record, DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    List selectByExampleWithPage(DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    List selectByExampleWithPage(DetailWithThirdPartyAccountExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    List getKeyBy(DetailWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    List getKeyBy(DetailWithThirdPartyAccountExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    int countByExample(DetailWithThirdPartyAccountExampleExtended example);
}