package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.DetailWithThirdPartyAccount;
import com.ctfo.account.dao.beans.DetailWithThirdPartyAccountExample;
import com.ctfo.account.dao.beans.DetailWithThirdPartyAccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DetailWithThirdPartyAccountDAOImpl extends SqlMapClientDaoSupport implements DetailWithThirdPartyAccountDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public DetailWithThirdPartyAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public void insert(DetailWithThirdPartyAccount record) {
        getSqlMapClientTemplate().insert("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int updateByPrimaryKey(DetailWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int updateByPrimaryKeySelective(DetailWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public List selectByExample(DetailWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public DetailWithThirdPartyAccount selectByPrimaryKey(String id) {
        DetailWithThirdPartyAccount key = new DetailWithThirdPartyAccount(){};
        key.setId(id);
        DetailWithThirdPartyAccount record = (DetailWithThirdPartyAccount) getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int deleteByExample(DetailWithThirdPartyAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        DetailWithThirdPartyAccount key = new DetailWithThirdPartyAccount(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int countByExample(DetailWithThirdPartyAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int updateByExampleSelective(DetailWithThirdPartyAccount record, DetailWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int updateByExample(DetailWithThirdPartyAccount record, DetailWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public List selectByExampleWithPage(DetailWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public List selectByExampleWithPage(DetailWithThirdPartyAccountExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public List getKeyBy(DetailWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public String getNameSpace() {
         return "TB_UPP_CHECK_PAY_ACCOUNT";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public List getKeyBy(DetailWithThirdPartyAccountExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    public int countByExample(DetailWithThirdPartyAccountExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_PAY_ACCOUNT.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_CHECK_PAY_ACCOUNT
     *
     * @abatorgenerated Mon Nov 03 13:56:53 CST 2014
     */
    private static class UpdateByExampleParms extends DetailWithThirdPartyAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, DetailWithThirdPartyAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}