package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.HAccount;
import com.ctfo.account.dao.beans.HAccountExample;
import com.ctfo.account.dao.beans.HAccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HAccountDAOImpl extends SqlMapClientDaoSupport implements HAccountDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public HAccountDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public void insert(HAccount record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int updateByPrimaryKey(HAccount record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int updateByPrimaryKeySelective(HAccount record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public List selectByExample(HAccountExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public HAccount selectByPrimaryKey(String id) {
		HAccount key = new HAccount() {
		};
		key.setId(id);
		HAccount record = (HAccount) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int deleteByExample(HAccountExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		HAccount key = new HAccount() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int countByExample(HAccountExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int updateByExampleSelective(HAccount record, HAccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int updateByExample(HAccount record, HAccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public List selectByExampleWithPage(HAccountExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public List selectByExampleWithPage(HAccountExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public List getKeyBy(HAccountExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_CASH_ACCOUNT_HISTORY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public List getKeyBy(HAccountExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	public int countByExample(HAccountExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_CASH_ACCOUNT_HISTORY.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_CASH_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Jul 20 16:52:08 CST 2015
	 */
	private static class UpdateByExampleParms extends HAccountExample {
		private Object record;

		public UpdateByExampleParms(Object record, HAccountExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}