package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.HSpecialAccount;
import com.ctfo.account.dao.beans.HSpecialAccountExample;
import com.ctfo.account.dao.beans.HSpecialAccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HSpecialAccountDAOImpl extends SqlMapClientDaoSupport implements HSpecialAccountDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public HSpecialAccountDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public void insert(HSpecialAccount record) {
		getSqlMapClientTemplate().insert("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int updateByPrimaryKey(HSpecialAccount record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int updateByPrimaryKeySelective(HSpecialAccount record) {
		int rows = getSqlMapClientTemplate().update("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public List selectByExample(HSpecialAccountExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public HSpecialAccount selectByPrimaryKey(String id) {
		HSpecialAccount key = new HSpecialAccount() {
		};
		key.setId(id);
		HSpecialAccount record = (HSpecialAccount) getSqlMapClientTemplate().queryForObject("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int deleteByExample(HSpecialAccountExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		HSpecialAccount key = new HSpecialAccount() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int countByExample(HSpecialAccountExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int updateByExampleSelective(HSpecialAccount record, HSpecialAccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int updateByExample(HSpecialAccount record, HSpecialAccountExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public List selectByExampleWithPage(HSpecialAccountExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public List selectByExampleWithPage(HSpecialAccountExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public List getKeyBy(HSpecialAccountExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public String getNameSpace() {
		return "TB_UPP_SUB_ACCOUNT_HISTORY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public List getKeyBy(HSpecialAccountExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	public int countByExample(HSpecialAccountExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_UPP_SUB_ACCOUNT_HISTORY.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT_HISTORY
	 * @abatorgenerated  Mon Nov 10 15:19:40 CST 2014
	 */
	private static class UpdateByExampleParms extends HSpecialAccountExample {
		private Object record;

		public UpdateByExampleParms(Object record, HSpecialAccountExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}