package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.ReconOfBatch;
import com.ctfo.account.dao.beans.ReconOfBatchExample;
import com.ctfo.account.dao.beans.ReconOfBatchExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ReconOfBatchDAOImpl extends SqlMapClientDaoSupport implements ReconOfBatchDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public ReconOfBatchDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public void insert(ReconOfBatch record) {
        getSqlMapClientTemplate().insert("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int updateByPrimaryKey(ReconOfBatch record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int updateByPrimaryKeySelective(ReconOfBatch record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public List selectByExample(ReconOfBatchExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public ReconOfBatch selectByPrimaryKey(String id) {
        ReconOfBatch key = new ReconOfBatch(){};
        key.setId(id);
        ReconOfBatch record = (ReconOfBatch) getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int deleteByExample(ReconOfBatchExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        ReconOfBatch key = new ReconOfBatch(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int countByExample(ReconOfBatchExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int updateByExampleSelective(ReconOfBatch record, ReconOfBatchExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int updateByExample(ReconOfBatch record, ReconOfBatchExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public List selectByExampleWithPage(ReconOfBatchExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public List selectByExampleWithPage(ReconOfBatchExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public List getKeyBy(ReconOfBatchExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public String getNameSpace() {
         return "TB_UPP_CHECK_ACCOUNT_BATCH";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public List getKeyBy(ReconOfBatchExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    public int countByExample(ReconOfBatchExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_ACCOUNT_BATCH.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    private static class UpdateByExampleParms extends ReconOfBatchExample {
        private Object record;

        public UpdateByExampleParms(Object record, ReconOfBatchExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}