package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.ReconOfBatch;
import com.ctfo.account.dao.beans.ReconOfBatchExample;
import com.ctfo.account.dao.beans.ReconOfBatchExampleExtended;
import java.util.List;

public interface ReconOfBatchDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    void insert(ReconOfBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int updateByPrimaryKey(ReconOfBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int updateByPrimaryKeySelective(ReconOfBatch record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    List selectByExample(ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    ReconOfBatch selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int deleteByExample(ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int countByExample(ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int updateByExampleSelective(ReconOfBatch record, ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int updateByExample(ReconOfBatch record, ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    List selectByExampleWithPage(ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    List selectByExampleWithPage(ReconOfBatchExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    List getKeyBy(ReconOfBatchExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    List getKeyBy(ReconOfBatchExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_ACCOUNT_BATCH
     *
     * @abatorgenerated Mon Nov 03 13:56:54 CST 2014
     */
    int countByExample(ReconOfBatchExampleExtended example);
}