package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.SpecialAccountDetail;
import com.ctfo.account.dao.beans.SpecialAccountDetailExample;
import com.ctfo.account.dao.beans.SpecialAccountDetailExampleExtended;
import java.util.List;

public interface SpecialAccountDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	void insert(SpecialAccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int updateByPrimaryKey(SpecialAccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int updateByPrimaryKeySelective(SpecialAccountDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	List selectByExample(SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	SpecialAccountDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int deleteByExample(SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int countByExample(SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int updateByExampleSelective(SpecialAccountDetail record,
			SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int updateByExample(SpecialAccountDetail record,
			SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	List selectByExampleWithPage(SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	List selectByExampleWithPage(
			SpecialAccountDetailExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	List getKeyBy(SpecialAccountDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	List getKeyBy(SpecialAccountDetailExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	int countByExample(SpecialAccountDetailExampleExtended example);
}