package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.SpecialAccountDetail;
import com.ctfo.account.dao.beans.SpecialAccountDetailExample;
import com.ctfo.account.dao.beans.SpecialAccountDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SpecialAccountDetailDAOImpl extends SqlMapClientDaoSupport implements SpecialAccountDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public SpecialAccountDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public void insert(SpecialAccountDetail record) {
		getSqlMapClientTemplate().insert(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int updateByPrimaryKey(SpecialAccountDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int updateByPrimaryKeySelective(SpecialAccountDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List selectByExample(SpecialAccountDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public SpecialAccountDetail selectByPrimaryKey(String id) {
		SpecialAccountDetail key = new SpecialAccountDetail() {
		};
		key.setId(id);
		SpecialAccountDetail record = (SpecialAccountDetail) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int deleteByExample(SpecialAccountDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		SpecialAccountDetail key = new SpecialAccountDetail() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int countByExample(SpecialAccountDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int updateByExampleSelective(SpecialAccountDetail record,
			SpecialAccountDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int updateByExample(SpecialAccountDetail record,
			SpecialAccountDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List selectByExampleWithPage(SpecialAccountDetailExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List selectByExampleWithPage(
			SpecialAccountDetailExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List getKeyBy(SpecialAccountDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public String getNameSpace() {
		return "TB_UPP_SUB_BOOK_ACCOUNT_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public List getKeyBy(SpecialAccountDetailExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	public int countByExample(SpecialAccountDetailExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_UPP_SUB_BOOK_ACCOUNT_INFO.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table UPP.TB_UPP_SUB_BOOK_ACCOUNT_INFO
	 * @abatorgenerated  Fri Feb 06 20:03:18 CST 2015
	 */
	private static class UpdateByExampleParms extends
			SpecialAccountDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				SpecialAccountDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}