package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.SpecialAccount;
import com.ctfo.account.dao.beans.SpecialAccountExample;
import com.ctfo.account.dao.beans.SpecialAccountExampleExtended;
import java.util.List;

public interface SpecialAccountDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	void insert(SpecialAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int updateByPrimaryKey(SpecialAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int updateByPrimaryKeySelective(SpecialAccount record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	List selectByExample(SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	SpecialAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int deleteByExample(SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int countByExample(SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int updateByExampleSelective(SpecialAccount record, SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int updateByExample(SpecialAccount record, SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	List selectByExampleWithPage(SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	List selectByExampleWithPage(SpecialAccountExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	List getKeyBy(SpecialAccountExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	List getKeyBy(SpecialAccountExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table UPP.TB_UPP_SUB_ACCOUNT
	 * @abatorgenerated  Mon Nov 10 15:19:33 CST 2014
	 */
	int countByExample(SpecialAccountExampleExtended example);
}