package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatform;
import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatformExample;
import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatformExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UnbalanceDetailWithBusPlatformDAOImpl extends SqlMapClientDaoSupport implements UnbalanceDetailWithBusPlatformDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public UnbalanceDetailWithBusPlatformDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public void insert(UnbalanceDetailWithBusPlatform record) {
        getSqlMapClientTemplate().insert("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int updateByPrimaryKey(UnbalanceDetailWithBusPlatform record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int updateByPrimaryKeySelective(UnbalanceDetailWithBusPlatform record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public List selectByExample(UnbalanceDetailWithBusPlatformExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public UnbalanceDetailWithBusPlatform selectByPrimaryKey(String id) {
        UnbalanceDetailWithBusPlatform key = new UnbalanceDetailWithBusPlatform(){};
        key.setId(id);
        UnbalanceDetailWithBusPlatform record = (UnbalanceDetailWithBusPlatform) getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int deleteByExample(UnbalanceDetailWithBusPlatformExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        UnbalanceDetailWithBusPlatform key = new UnbalanceDetailWithBusPlatform(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int countByExample(UnbalanceDetailWithBusPlatformExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int updateByExampleSelective(UnbalanceDetailWithBusPlatform record, UnbalanceDetailWithBusPlatformExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int updateByExample(UnbalanceDetailWithBusPlatform record, UnbalanceDetailWithBusPlatformExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceDetailWithBusPlatformExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceDetailWithBusPlatformExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public List getKeyBy(UnbalanceDetailWithBusPlatformExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public String getNameSpace() {
         return "TB_UPP_CHECK_STORE_DIVERGENCE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public List getKeyBy(UnbalanceDetailWithBusPlatformExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    public int countByExample(UnbalanceDetailWithBusPlatformExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_STORE_DIVERGENCE.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    private static class UpdateByExampleParms extends UnbalanceDetailWithBusPlatformExample {
        private Object record;

        public UpdateByExampleParms(Object record, UnbalanceDetailWithBusPlatformExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}