package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.UnbalanceTradeWithThirdPartyAccount;
import com.ctfo.account.dao.beans.UnbalanceTradeWithThirdPartyAccountExample;
import com.ctfo.account.dao.beans.UnbalanceTradeWithThirdPartyAccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UnbalanceTradeWithThirdPartyAccountDAOImpl extends SqlMapClientDaoSupport implements UnbalanceTradeWithThirdPartyAccountDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public UnbalanceTradeWithThirdPartyAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public void insert(UnbalanceTradeWithThirdPartyAccount record) {
        getSqlMapClientTemplate().insert("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int updateByPrimaryKey(UnbalanceTradeWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int updateByPrimaryKeySelective(UnbalanceTradeWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public List selectByExample(UnbalanceTradeWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public UnbalanceTradeWithThirdPartyAccount selectByPrimaryKey(String id) {
        UnbalanceTradeWithThirdPartyAccount key = new UnbalanceTradeWithThirdPartyAccount(){};
        key.setId(id);
        UnbalanceTradeWithThirdPartyAccount record = (UnbalanceTradeWithThirdPartyAccount) getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int deleteByExample(UnbalanceTradeWithThirdPartyAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        UnbalanceTradeWithThirdPartyAccount key = new UnbalanceTradeWithThirdPartyAccount(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int countByExample(UnbalanceTradeWithThirdPartyAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int updateByExampleSelective(UnbalanceTradeWithThirdPartyAccount record, UnbalanceTradeWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int updateByExample(UnbalanceTradeWithThirdPartyAccount record, UnbalanceTradeWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceTradeWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceTradeWithThirdPartyAccountExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public List getKeyBy(UnbalanceTradeWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public String getNameSpace() {
         return "TB_UPP_CHECK_TRADE_DIVERGENCE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public List getKeyBy(UnbalanceTradeWithThirdPartyAccountExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    public int countByExample(UnbalanceTradeWithThirdPartyAccountExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECK_TRADE_DIVERGENCE.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_CHECK_TRADE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:49 CST 2014
     */
    private static class UpdateByExampleParms extends UnbalanceTradeWithThirdPartyAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, UnbalanceTradeWithThirdPartyAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}