package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccount;
import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccountExample;
import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccountExampleExtended;
import java.util.List;

public interface UnbalanceHandlerWithThirdPartyAccountDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    void insert(UnbalanceHandlerWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int updateByPrimaryKey(UnbalanceHandlerWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int updateByPrimaryKeySelective(UnbalanceHandlerWithThirdPartyAccount record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    List selectByExample(UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    UnbalanceHandlerWithThirdPartyAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int deleteByExample(UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int countByExample(UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int updateByExampleSelective(UnbalanceHandlerWithThirdPartyAccount record, UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int updateByExample(UnbalanceHandlerWithThirdPartyAccount record, UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    List selectByExampleWithPage(UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    List selectByExampleWithPage(UnbalanceHandlerWithThirdPartyAccountExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    List getKeyBy(UnbalanceHandlerWithThirdPartyAccountExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    List getKeyBy(UnbalanceHandlerWithThirdPartyAccountExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    int countByExample(UnbalanceHandlerWithThirdPartyAccountExampleExtended example);
}