package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatform;
import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatformExample;
import com.ctfo.account.dao.beans.UnbalanceDetailWithBusPlatformExampleExtended;
import java.util.List;

public interface UnbalanceDetailWithBusPlatformDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    void insert(UnbalanceDetailWithBusPlatform record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int updateByPrimaryKey(UnbalanceDetailWithBusPlatform record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int updateByPrimaryKeySelective(UnbalanceDetailWithBusPlatform record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    List selectByExample(UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    UnbalanceDetailWithBusPlatform selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int deleteByExample(UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int countByExample(UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int updateByExampleSelective(UnbalanceDetailWithBusPlatform record, UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int updateByExample(UnbalanceDetailWithBusPlatform record, UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    List selectByExampleWithPage(UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    List selectByExampleWithPage(UnbalanceDetailWithBusPlatformExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    List getKeyBy(UnbalanceDetailWithBusPlatformExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    List getKeyBy(UnbalanceDetailWithBusPlatformExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECK_STORE_DIVERGENCE
     *
     * @abatorgenerated Mon Nov 03 13:56:44 CST 2014
     */
    int countByExample(UnbalanceDetailWithBusPlatformExampleExtended example);
}