package com.ctfo.upp.accountservice.account.dao;

import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccount;
import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccountExample;
import com.ctfo.account.dao.beans.UnbalanceHandlerWithThirdPartyAccountExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UnbalanceHandlerWithThirdPartyAccountDAOImpl extends SqlMapClientDaoSupport implements UnbalanceHandlerWithThirdPartyAccountDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public UnbalanceHandlerWithThirdPartyAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public void insert(UnbalanceHandlerWithThirdPartyAccount record) {
        getSqlMapClientTemplate().insert("TB_UPP_CHECKACC_HANDLE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int updateByPrimaryKey(UnbalanceHandlerWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECKACC_HANDLE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int updateByPrimaryKeySelective(UnbalanceHandlerWithThirdPartyAccount record) {
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECKACC_HANDLE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public List selectByExample(UnbalanceHandlerWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public UnbalanceHandlerWithThirdPartyAccount selectByPrimaryKey(String id) {
        UnbalanceHandlerWithThirdPartyAccount key = new UnbalanceHandlerWithThirdPartyAccount(){};
        key.setId(id);
        UnbalanceHandlerWithThirdPartyAccount record = (UnbalanceHandlerWithThirdPartyAccount) getSqlMapClientTemplate().queryForObject("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int deleteByExample(UnbalanceHandlerWithThirdPartyAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECKACC_HANDLE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        UnbalanceHandlerWithThirdPartyAccount key = new UnbalanceHandlerWithThirdPartyAccount(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_UPP_CHECKACC_HANDLE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int countByExample(UnbalanceHandlerWithThirdPartyAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECKACC_HANDLE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int updateByExampleSelective(UnbalanceHandlerWithThirdPartyAccount record, UnbalanceHandlerWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECKACC_HANDLE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int updateByExample(UnbalanceHandlerWithThirdPartyAccount record, UnbalanceHandlerWithThirdPartyAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_UPP_CHECKACC_HANDLE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceHandlerWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public List selectByExampleWithPage(UnbalanceHandlerWithThirdPartyAccountExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public List getKeyBy(UnbalanceHandlerWithThirdPartyAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public String getNameSpace() {
         return "TB_UPP_CHECKACC_HANDLE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public List getKeyBy(UnbalanceHandlerWithThirdPartyAccountExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_UPP_CHECKACC_HANDLE.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    public int countByExample(UnbalanceHandlerWithThirdPartyAccountExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_UPP_CHECKACC_HANDLE.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table UPP.TB_UPP_CHECKACC_HANDLE
     *
     * @abatorgenerated Mon Nov 03 13:56:50 CST 2014
     */
    private static class UpdateByExampleParms extends UnbalanceHandlerWithThirdPartyAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, UnbalanceHandlerWithThirdPartyAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}